/* ---------------------------------------------------------------------------
 * 용어 사전 데이터
 *
 * 용어를 추가할 때는 아래 TERMS 배열에 객체 하나만 더하면 됩니다.
 * 카드 · 검색 · 분류 탭 · 개수는 index.html이 알아서 그립니다.
 *
 *   id      앵커 URL이 됩니다. 영문 소문자와 하이픈만. (예: '#ux')
 *   emoji   용어 앞에 붙는 이모지 하나
 *   term    한글/표기 용어
 *   en      원어 (없으면 생략)
 *   part    이 용어를 다루는 PART. TERM_CATEGORIES의 id 중 하나
 *   kind    용어의 성격. TERM_KINDS의 id 중 하나 (concept / tool / lang)
 *   short   목록에 바로 보이는 설명. 2~3줄, 초보자가 읽고 바로 이해할 수 있게.
 *   logo    공식 로고 SVG의 상대 경로 (예: 'logos/python.svg'). 이름 옆에 작게 표시됩니다. (없으면 생략)
 *   body    펼쳤을 때 나오는 자세한 설명. 문단 배열.
 *   note    주의할 점 (없으면 생략)
 *   spectrum 두 용어를 한 축으로 비교하는 막대. { leftLabel, rightLabel, value(0~100) }
 *            같은 축(leftLabel/rightLabel)을 비교 대상 카드 여러 개에 나눠 붙이면
 *            서로 다른 위치의 점으로 비교가 됩니다. (없으면 생략)
 *   flow    관계·과정을 보여주는 Mermaid flowchart 문법 문자열. 펼쳤을 때 다이어그램으로
 *           그려집니다. (없으면 생략)
 *   related 관련 용어 id 배열 (없으면 생략)
 *
 * 걸러 보는 축이 두 개입니다. 위쪽 줄은 커리큘럼 PART(언제 배우는가),
 * 아래쪽 줄은 성격(개념인가 도구인가). 두 축은 함께 적용됩니다.
 *
 * PART 분류는 커리큘럼을 그대로 씁니다. 용어가 늘어나도 "이 말은 몇 주차에
 * 나오는가"로 정리되기 때문에, 새 분류를 고민할 필요가 없습니다.
 * 새 PART의 용어를 넣을 때는 TERM_CATEGORIES에 한 줄을 추가하면 탭이 생깁니다.
 *
 * JSON이 아니라 .js인 이유: JSON + fetch는 파일을 더블클릭해 여는
 * 로컬 환경(file://)에서 CORS로 막힙니다. 이 방식은 로컬과 GitHub Pages
 * 양쪽에서 모두 동작합니다.
 * ------------------------------------------------------------------------- */

const TERM_CATEGORIES = [
  { id: 'part01', no: '01', name: '오리엔테이션' },
  { id: 'part02', no: '02', name: 'AI 실전 활용' },
  { id: 'part03', no: '03', name: 'UX/UI 디자인' },
  { id: 'part04', no: '04', name: '노코드 프로토타이핑' },
  { id: 'part05', no: '05', name: '서비스 기획' },
  { id: 'part06', no: '06', name: '데이터 분석 & 머신러닝' },
  { id: 'part07', no: '07', name: 'LLM · RAG · Agent' },
  { id: 'part08', no: '08', name: '해커톤' },
];

const TERM_KINDS = [
  { id: 'concept', label: '기본 개념' },
  { id: 'tool',    label: '도구' },
  { id: 'deploy',  label: '배포도구' },
  { id: 'lang',    label: '언어' },
];

const TERMS = [
  /* ---- PART 01. 오리엔테이션 ---- */
  {
    id: 'portfolio',
    emoji: '📁',
    term: '포트폴리오',
    en: 'Portfolio',
    part: 'part01',
    kind: 'concept',
    short: '그동안 만든 결과물을 남에게 보여줄 수 있게 모아서 정리한 것이에요. 프로젝트 스크린샷, 코드 링크, 짧은 설명을 한곳에 모아 두면 "제가 무엇을 할 수 있는지"를 말로 설명하는 것보다 훨씬 빠르게 전달됩니다. 취업이나 이직을 준비할 때 이력서보다 먼저 열어 보는 경우가 많아요. 📁',
    body: [
      '1회차에 만드는 것과 8회차(마지막)에 정리하는 것이 같은 포트폴리오입니다. 과정을 시작할 때 미리 틀을 잡아 두고, 프로젝트를 하나씩 만들 때마다 채워 넣다가, 마지막에 GitHub 위에 정리해서 완성합니다.',
      '완성된 결과물만 담을 필요는 없습니다. 왜 이 프로젝트를 만들었는지, 어떤 문제를 어떻게 풀었는지 같은 <strong>과정</strong>을 함께 적어 두면 보는 사람이 실력을 훨씬 더 잘 가늠할 수 있어요.',
    ],
    note: '완벽하게 만들고 나서 한꺼번에 공개하려고 미루기보다, 프로젝트 하나가 끝날 때마다 바로 추가해 두는 편이 낫습니다. 미루면 결국 마지막 주에 몰아서 하게 됩니다.',
    related: ['github', 'github-pages', 'capstone'],
  },
  {
    id: 'team-building',
    emoji: '🤝',
    term: '팀 빌딩',
    en: 'Team Building',
    part: 'part01',
    kind: 'concept',
    short: '함께 프로젝트를 진행할 팀을 꾸리고, 팀원들과 서로를 알아가는 활동이에요. 단순히 인원을 채우는 것이 아니라, 각자 무엇을 잘하고 어떤 방식으로 일하는지 미리 확인해서 손발이 맞는 팀을 만드는 과정입니다. 이 과정에서는 2회차와 30회차, 두 번에 걸쳐 진행됩니다. 🤝',
    body: [
      '2회차의 팀 빌딩은 서로 얼굴을 익히고 함께 일하는 방식을 맞춰 보는 자리에 가깝습니다. 30회차의 팀 빌딩은 캡스톤 프로젝트를 앞두고, 실제로 몇 주간 함께 만들 팀을 구체적으로 정하는 자리라 성격이 조금 다릅니다.',
      '기술 실력만큼이나 <strong>일정과 역할을 어떻게 나눌지</strong>가 팀의 성패를 가릅니다. 누가 기획을 맡고 누가 화면을 만들지 초반에 정해 두면 나중에 혼선이 줄어듭니다.',
    ],
    related: ['capstone', 'hackathon', 'portfolio'],
  },

  /* ---- PART 02. AI 실전 활용 ---- */
  {
    id: 'generative-ai',
    emoji: '💫',
    term: '생성형 AI',
    en: 'Generative AI',
    part: 'part02',
    kind: 'concept',
    short: '데이터를 분류하거나 예측하는 데 그치지 않고, 텍스트·이미지·코드·음성처럼 이전에 없던 콘텐츠를 새로 만들어 내는 AI를 말해요. "고양이 사진을 골라내는" AI는 판별형이지만, "고양이 그림을 그려 주는" AI는 생성형입니다. 이 과정에서 배우는 도구 대부분이 이 범주에 속합니다. ✨',
    body: [
      '텍스트를 생성하는 LLM(ChatGPT, Claude)뿐 아니라 이미지·영상·음악을 만드는 도구까지 전부 생성형 AI의 하위 갈래입니다. "생성형 AI"는 이들을 아우르는 더 큰 우산 개념이고, LLM은 그중 언어에 특화된 한 종류예요.',
      '2022년 말 ChatGPT가 널리 쓰이기 시작하면서 이 표현도 함께 퍼졌습니다. 이 과정의 바이브코딩·프롬프트 엔지니어링은 결국 "생성형 AI를 실무에서 잘 부려 쓰는 법"을 배우는 과정이라고 볼 수 있어요.',
    ],
    note: '그럴듯하게 지어내지만 틀린 내용(환각, hallucination)을 만들어 낼 수 있다는 점은 어떤 생성형 AI를 쓰든 동일하게 조심해야 합니다. ⚠️',
    related: ['llm', 'vibe-coding', 'prompt-engineering', 'chatgpt', 'claude', 'gemini', 'grok'],
  },
  {
    id: 'chatgpt',
    emoji: '🗨️',
    term: 'ChatGPT',
    en: 'OpenAI',
    part: 'part02',
    kind: 'tool',
    short: 'OpenAI가 2022년 11월에 공개해 생성형 AI 챗봇 붐을 일으킨 대화형 AI예요. 질문에 답하는 것은 물론 글쓰기·번역·코드 작성까지 대화하듯 시킬 수 있고, 지금 이 과정에서 쓰는 도구 대부분이 이 챗봇 이후 쏟아져 나왔습니다. 🤖',
    body: [
      '공개 5일 만에 사용자 100만 명을 넘기며 "AI에게 말로 시킨다"는 경험을 대중에게 처음 각인시킨 서비스입니다. 이후 Claude·Gemini·Grok 같은 경쟁 서비스가 잇따라 나왔습니다.',
      'OpenAI의 코딩 도구인 <strong>Codex</strong>도 ChatGPT와 같은 계열의 모델 위에서 동작합니다.',
    ],
    spectrum: { leftLabel: '먼저 나온 챗봇', rightLabel: '나중에 나온 챗봇', value: 5 },
    related: ['codex', 'llm', 'generative-ai'],
  },
  {
    id: 'claude',
    emoji: '🟠',
    term: 'Claude',
    en: 'Anthropic',
    part: 'part02',
    kind: 'tool',
    short: 'Anthropic이 만든 대화형 AI 챗봇이자, 이 커리큘럼에서 가장 많이 쓰는 LLM이에요. 질문에 답하는 것을 넘어 글쓰기·코드 작성·분석까지 폭넓게 돕고, Claude Code·Claude Design처럼 이 이름을 단 여러 도구가 전부 이 모델 위에서 동작합니다. 🟠',
    body: [
      'OpenAI 출신 연구자들이 2021년에 세운 Anthropic이 만든 챗봇으로, 2023년 3월 첫 버전이 나온 뒤로 계속 새 버전이 이어지고 있습니다. "안전하게 도움이 되는 AI"를 표방하는 회사 철학이 응답 스타일에도 묻어납니다.',
      '이 과정에서 쓰는 <strong>Claude Code</strong>, <strong>Claude Design</strong>은 전부 "Claude"라는 같은 모델을 서로 다른 용도(터미널 코딩, 디자인 초안)에 맞게 감싼 도구입니다. 모델 이름과 도구 이름을 헷갈리지 않는 것이 중요해요.',
    ],
    spectrum: { leftLabel: '먼저 나온 챗봇', rightLabel: '나중에 나온 챗봇', value: 25 },
    related: ['claude-code', 'claude-design', 'llm', 'generative-ai'],
  },
  {
    id: 'grok',
    emoji: '🛰️',
    term: 'Grok',
    en: 'xAI · X',
    part: 'part02',
    kind: 'tool',
    short: '일론 머스크가 세운 xAI가 만든 대화형 AI로, X(구 트위터) 앱 안에 기본으로 들어가 있는 것이 가장 큰 특징이에요. 2023년 11월 X Premium+ 구독자 대상으로 처음 공개됐습니다. 🛰️',
    body: [
      '다른 챗봇과 달리 X에 올라오는 실시간 게시글을 참고해 답할 수 있다는 점을 내세웁니다. 별도 앱보다 X 서비스 안에서 바로 마주치는 경우가 많습니다.',
      'xAI는 2023년 일론 머스크가 세운 회사입니다. 2026년 2월 SpaceX가 xAI를 인수하면서 지금은 SpaceX 산하 회사가 되었고, Tesla는 이 합병에 포함되지 않아 별도 회사로 남아 있습니다.',
    ],
    spectrum: { leftLabel: '먼저 나온 챗봇', rightLabel: '나중에 나온 챗봇', value: 65 },
    related: ['llm', 'generative-ai'],
  },
  {
    id: 'gemini',
    emoji: '♊',
    term: 'Gemini',
    en: 'Google',
    part: 'part02',
    kind: 'tool',
    short: '구글이 만든 대화형 AI로, 원래 이름은 Bard였다가 2024년 초 지금의 Gemini로 바뀌었어요. 구글 검색·Gmail·문서 같은 구글 서비스 곳곳에 함께 들어가 있는 것이 특징입니다. ♊',
    body: [
      '2023년 3월 "Bard"라는 이름으로 처음 나왔다가, 2023년 12월 새 모델 Gemini가 나오면서 2024년 2월 서비스 이름도 Gemini로 통일됐습니다. 아래 스펙트럼의 위치는 전신인 Bard가 아니라, 지금 이름인 <strong>"Gemini"라는 모델이 나온 시점</strong>(2023년 12월)을 기준으로 삼았습니다.',
      '독립된 챗봇 화면뿐 아니라 이 과정에서 다루는 <strong>Google AI Studio</strong>, <strong>Firebase</strong> 같은 구글 도구 안에서도 같은 모델이 쓰입니다.',
    ],
    spectrum: { leftLabel: '먼저 나온 챗봇', rightLabel: '나중에 나온 챗봇', value: 80 },
    related: ['google-ai-studio', 'llm', 'generative-ai'],
  },
  {
    id: 'vibe-coding',
    emoji: '💬',
    term: '바이브코딩',
    en: 'Vibe Coding',
    part: 'part02',
    kind: 'concept',
    short: '코드를 한 줄씩 직접 타이핑하는 대신, AI에게 "이런 걸 만들어 줘"라고 말로 설명해서 만드는 방식이에요. 예를 들어 "할 일 목록 앱을 만들어 줘"라고 말하면 AI가 실제로 동작하는 코드를 짜 줍니다. 어려운 문법을 외우지 못해도 괜찮고, 대신 원하는 것을 또렷하게 설명하는 능력이 곧 실력이 됩니다. ✨',
    body: [
      '예를 들어 "메모를 적고 저장할 수 있는 간단한 웹페이지를 만들어 줘"라고 말하면 AI가 코드를 만들어 줍니다. 그걸 실행해 보고 "글씨가 너무 작아, 키워 줘"처럼 다시 말하며 원하는 모습에 가까워지는 식이에요.',
      '2025년 초 앤드레이 카파시(Andrej Karpathy)라는 개발자가 쓴 표현에서 퍼졌습니다. 이 과정에서 배우는 도구 대부분이 이 방식을 전제로 하고 있어요.',
    ],
    note: 'AI가 만든 코드를 전혀 이해하지 않은 채 계속 쌓기만 하면, 나중에 문제가 생겼을 때 어디를 고쳐야 할지 알 수 없게 됩니다. 실습에서는 "왜 이렇게 동작하는지" 한 번씩 확인하는 습관을 함께 기릅니다. 🧐',
    flow: 'flowchart LR\n' +
          'A["말로 설명하기"] --> B["AI가 코드 작성"]\n' +
          'B --> C["실행해서 확인"]\n' +
          'C -- "고칠 점 발견" --> A\n' +
          'C -- "마음에 듦" --> D["완성"]',
    related: ['prompt-engineering', 'llm', 'lovable', 'v0', 'electron'],
  },
  {
    id: 'prompt-engineering',
    emoji: '🎯',
    term: '프롬프트 엔지니어링',
    en: 'Prompt Engineering',
    part: 'part02',
    kind: 'concept',
    short: 'AI에게 원하는 답을 얻어 내기 위해 질문을 잘 다듬는 기술이에요. 같은 것을 물어도 어떻게 묻느냐에 따라 결과가 확 달라지는데, 예를 들어 "요약해 줘"보다 "세 문장으로, 초등학생도 이해하게 요약해 줘"가 훨씬 쓸 만한 답을 줍니다. 요령이 있고, 배우면 늡니다. 📝',
    body: [
      '"글 써 줘"와 "중학생도 읽을 수 있게, 500자 정도로, 예시 두 개를 넣어서 블로그 글을 써 줘"의 결과는 완전히 다릅니다. 뒤쪽처럼 <strong>역할·조건·예시</strong>를 함께 주는 것이 기본기예요.',
      '한 번에 완벽한 질문을 만들 필요는 없습니다. 답을 보고 "여기는 좀 더 짧게"처럼 고쳐 나가는 과정 전체가 프롬프트 엔지니어링입니다.',
      'AI가 알아야 할 배경 정보를 어디까지 알려 줄지 정하는 일(컨텍스트 설계)도 함께 다룹니다. 배경을 모르면 AI는 일반적인 답만 내놓거든요.',
    ],
    related: ['llm', 'vibe-coding'],
  },
  {
    id: 'html',
    emoji: '📄',
    term: 'HTML',
    en: 'HyperText Markup Language',
    part: 'part02',
    kind: 'lang',
    short: '웹페이지의 뼈대를 적는 언어예요. "여기는 제목, 여기는 문단, 여기는 버튼"처럼 화면에 무엇이 있는지를 알려 주고, 브라우저는 이 정보를 보고 화면을 그려 줍니다. 지금 보고 계신 이 페이지도 HTML로 되어 있어요. 🧱',
    body: [
      '계산을 하거나 판단을 내리는 프로그래밍 언어라기보다는, 문서의 구조를 적어 두는 표기법에 가깝습니다. 그래서 처음 보기에 어렵지 않아요.',
      '전부 외울 필요는 없습니다. AI가 만들어 준 결과를 열어 보고 <strong>"아, 제목이 여기고 버튼이 저기구나"</strong> 정도만 알아볼 수 있으면 수업을 따라가는 데 충분합니다.',
    ],
    related: ['github-pages', 'vibe-coding', 'electron', 'javascript', 'css'],
  },
  {
    id: 'github',
    emoji: '🐙',
    term: 'GitHub',
    en: 'github.com',
    part: 'part02',
    kind: 'deploy',
    short: '내가 짠 코드를 온라인에 저장하고, 변경 이력을 기록하고, 다른 사람과 함께 작업할 수 있게 해 주는 서비스예요. 예를 들어 여러 명이 같은 프로젝트를 동시에 고쳐도, 누가 언제 무엇을 바꿨는지 전부 기록에 남습니다. 이 과정에서 만드는 결과물은 거의 다 여기에 올려 두고 시작합니다. 🐙',
    body: [
      'Git이라는 버전 관리 도구를 웹에서 편하게 쓸 수 있게 만든 서비스입니다. 코드를 "커밋" 단위로 저장해 두면, 언제 무엇이 왜 바뀌었는지 나중에도 전부 되짚어 볼 수 있어요.',
      '단순 저장소를 넘어 GitHub Pages(웹사이트 배포), GitHub Actions(자동화), Pull Request(협업 리뷰) 같은 기능이 모두 이 위에서 돌아갑니다. 이 과정에서 만나는 배포 도구 대부분이 결국 GitHub 저장소를 출발점으로 삼습니다.',
    ],
    related: ['github-pages', 'github-actions', 'cloudflare-pages', 'vercel', 'netlify', 'git-commit-cycle', 'git-branch', 'git-merge'],
  },
  {
    id: 'github-pages',
    emoji: '🌐',
    term: 'GitHub Pages',
    en: 'pages.github.com',
    part: 'part02',
    kind: 'deploy',
    short: 'GitHub에 올린 파일을 그대로 웹사이트로 띄워 주는 무료 서비스예요. 서버를 따로 빌리지 않아도 인터넷 주소가 생기고, 코드를 고치면 몇 분 안에 그대로 반영됩니다. 지금 보고 계신 이 사이트도 이걸로 만들어졌어요. 🆓',
    body: [
      '파일을 고쳐서 올리면 몇 분 안에 실제 사이트에 반영됩니다. 만든 것을 남에게 보여 주기 가장 빠른 방법이라 수업 초반부터 씁니다.',
      '다만 HTML·이미지처럼 <strong>완성된 파일을 보여 주는 것</strong>까지가 역할입니다. 회원가입이나 데이터 저장처럼 뒷단이 필요한 기능은 다른 방법을 씁니다.',
      '사전 학습 영상에 10분짜리 실습 영상을 넣어 두었으니 함께 보시면 좋습니다.',
    ],
    note: '무료 플랜은 <strong>private 저장소에서는 지원되지 않습니다.</strong> 저장소를 비공개로 바꾸면 이 기능도 함께 꺼집니다. 🔒',
    spectrum: { leftLabel: '심플', rightLabel: '기능 많음', value: 15 },
    related: ['html', 'landing-page', 'github-actions', 'github', 'cloudflare-pages', 'pwa'],
  },
  {
    id: 'github-actions',
    emoji: '⚙️',
    term: 'GitHub Actions',
    en: 'github.com/features/actions',
    part: 'part02',
    kind: 'tool',
    short: 'GitHub 저장소에 코드를 올리면(push), 미리 정해 둔 작업을 자동으로 대신 실행해 주는 기능이에요. "코드를 고쳐서 올리면 알아서 사이트에 반영해라" 같은 심부름을 로봇에게 맡기는 것과 비슷합니다. 테스트 실행, 배포처럼 반복되는 작업을 사람이 손으로 안 해도 되게 해 줍니다. 🤖',
    body: [
      '사람이 매번 손으로 "확인하고 → 반영하고" 같은 절차를 반복하지 않도록, GitHub이 정해진 순간(코드 push, PR 생성 등)마다 미리 적어 둔 절차를 대신 실행해 줍니다. 이 절차는 저장소 안 <code>.github/workflows</code> 폴더의 설정 파일 하나로 정해 둡니다.',
      'GitHub Pages 사이트도 뒤에서는 이 기능이 함께 돌아가는 경우가 많습니다. 파일을 올리기만 하면 GitHub Actions가 그걸 감지해서 사이트에 반영하는 작업을 대신 처리하는 식이에요.',
    ],
    note: '설정 파일을 직접 쓸 일이 당장 없어도, "왜 커밋했는데 사이트 반영까지 몇 분 걸리지?"의 답이 바로 이 자동 실행 시간이라는 것만 알아도 충분합니다. ⏱️',
    flow: 'flowchart LR\n' +
          'A["코드 push"] --> B["GitHub Actions 감지"]\n' +
          'B --> C["빌드"]\n' +
          'C --> D["배포"]',
    related: ['github-pages', 'html'],
  },
  {
    id: 'cloudflare-pages',
    emoji: '🌩️',
    term: 'Cloudflare Pages',
    en: 'pages.cloudflare.com',
    part: 'part02',
    kind: 'deploy',
    short: 'GitHub 저장소를 연결해 두면 코드를 올릴 때마다 자동으로 빌드해서 띄워 주는 무료 호스팅 서비스예요. GitHub Pages와 하는 일은 비슷하지만, Cloudflare의 전 세계 서버망을 타고 나가서 어디서 접속하든 더 빠르게 열립니다. 그 대신 기능도 더 많아서, PR 미리보기 배포 같은 것도 기본으로 제공합니다. ☁️',
    body: [
      'GitHub Pages처럼 파일을 올리기만 하면 인터넷 주소가 생깁니다. 다만 뒤에서 Cloudflare의 CDN(전 세계 곳곳에 흩어진 서버망)을 타기 때문에, 어느 나라에서 접속하든 가까운 서버가 대신 응답해 빠르게 열립니다.',
      '가장 눈에 띄는 차이는 <strong>미리보기 배포</strong>입니다. 코드를 고쳐서 PR(Pull Request)을 올리면, 그 PR 전용의 별도 주소가 자동으로 하나 더 생겨서 "합치기 전에" 실제로 눌러 보며 검토할 수 있습니다.',
      '정적인 화면뿐 아니라 서버를 따로 두지 않고도 돌아가는 간단한 뒷단 코드(Cloudflare Functions)까지 같은 곳에 올릴 수 있어서, "그냥 보여 주기"를 넘어서는 기능이 필요해지면 GitHub Pages 대신 넘어가 볼 만합니다.',
    ],
    note: 'GitHub Pages와 달리 <strong>private 저장소를 연결해도 배포가 계속됩니다.</strong> "소스는 비공개, 결과물만 공개"하고 싶을 때 넘어가는 이유 중 하나입니다. 🔀',
    spectrum: { leftLabel: '심플', rightLabel: '기능 많음', value: 60 },
    related: ['github-pages', 'github-actions', 'github', 'vercel', 'netlify', 'html'],
  },
  {
    id: 'vercel',
    emoji: '▲',
    term: 'Vercel',
    en: 'vercel.com',
    part: 'part02',
    kind: 'deploy',
    short: 'GitHub 저장소를 연결하면 코드를 올릴 때마다 자동으로 배포해 주는 호스팅 서비스예요. Next.js를 만든 회사이기도 해서, 특히 Next.js 프로젝트를 올리면 별다른 설정 없이도 가장 잘 맞게 동작합니다. PR을 올리면 그 PR 전용의 미리보기 주소도 자동으로 생깁니다. ▲',
    body: [
      'Cloudflare Pages·GitHub Pages와 마찬가지로 코드를 push하면 자동으로 사이트가 반영되고, PR을 올리면 그 PR 전용 미리보기 주소가 따로 생깁니다.',
      '이 과정에서 쓰는 <strong>V0</strong>(화면을 코드로 뽑아 주는 도구)도 Vercel이 만든 서비스예요. 그래서 V0로 뽑은 화면을 그대로 Vercel에 올려 배포하는 흐름이 자연스럽게 이어집니다.',
    ],
    spectrum: { leftLabel: '심플', rightLabel: '기능 많음', value: 75 },
    related: ['v0', 'cloudflare-pages', 'github-pages', 'netlify', 'nextjs'],
  },
  {
    id: 'netlify',
    emoji: '🪂',
    term: 'Netlify',
    en: 'netlify.com',
    part: 'part02',
    kind: 'deploy',
    short: 'GitHub 저장소를 연결해서 정적 사이트를 자동으로 배포해 주는 서비스예요. GitHub Pages·Cloudflare Pages·Vercel과 목적이 같은, 이 분야의 원조격 서비스입니다. PR 미리보기, 폼 제출 받기 같은 기능을 일찍부터 갖추고 있어서 지금도 많이 쓰입니다. 🪂',
    body: [
      'PR 미리보기 배포, 폼 제출 받기, 서버 없이 돌아가는 간단한 뒷단 함수(Functions) 같은 기능을 일찍부터 제공해 온 서비스라, 지금 다른 서비스들이 따라 하는 기능 상당수가 여기서 먼저 나왔습니다.',
      '기능만 보면 Cloudflare Pages·Vercel과 크게 다르지 않아서, 이 중 무엇을 쓰느냐는 취향과 무료 플랜 조건 차이에 가깝습니다.',
    ],
    spectrum: { leftLabel: '심플', rightLabel: '기능 많음', value: 65 },
    related: ['cloudflare-pages', 'vercel', 'github-pages'],
  },
  {
    id: 'javascript',
    emoji: '🟨',
    term: 'JavaScript',
    en: 'JS',
    part: 'part02',
    kind: 'lang',
    short: '웹페이지를 "움직이게" 만드는 언어예요. HTML이 뼈대라면, JavaScript는 버튼을 눌렀을 때 반응하고 화면이 바뀌는 것 같은 동작을 담당합니다. 지금은 브라우저를 넘어 서버·앱까지 이 언어 하나로 만들 수 있을 만큼 쓰임새가 넓어졌습니다. 🟨',
    body: [
      '처음에는 브라우저 안에서만 돌아가는 언어였지만, 지금은 서버·앱·데스크톱 프로그램까지 이 언어 하나로 만들 수 있을 만큼 쓰임새가 넓어졌습니다. React, Next.js 같은 도구들도 모두 이 언어 위에서 동작합니다.',
      'AI 코딩 도구가 만들어 주는 웹 화면의 "동작하는 부분"은 대부분 이 언어로 되어 있습니다. 문법을 몰라도, 코드를 열었을 때 <strong>"아, 여기가 움직이는 부분이구나"</strong> 정도만 알아도 충분합니다.',
    ],
    related: ['html', 'css', 'typescript', 'react'],
  },
  {
    id: 'css',
    emoji: '💅',
    term: 'CSS',
    en: 'Cascading Style Sheets',
    part: 'part02',
    kind: 'lang',
    short: 'HTML로 짠 뼈대를 예쁘게 꾸미는 언어예요. 색깔, 글씨 크기, 여백, 배치처럼 "보이는 방식"을 전부 여기서 정합니다. 같은 HTML이라도 CSS를 어떻게 입히느냐에 따라 완전히 다른 느낌의 화면이 됩니다. 💅',
    body: [
      '같은 HTML이라도 CSS를 어떻게 입히느냐에 따라 완전히 다른 느낌의 화면이 됩니다. "제목을 가운데로, 버튼은 파란색으로" 같은 지시를 코드로 적어 두는 것이라고 생각하면 쉽습니다.',
      '직접 손으로 다 짜지 않아도, <strong>Tailwind CSS</strong> 같은 도구를 쓰면 미리 정해진 짧은 이름(클래스)만 붙여서 빠르게 꾸밀 수 있습니다.',
    ],
    related: ['html', 'javascript', 'tailwind-css'],
  },
  {
    id: 'typescript',
    emoji: '🔷',
    term: 'TypeScript',
    en: 'TS',
    part: 'part02',
    kind: 'lang',
    short: 'JavaScript에 "이 값은 숫자, 이건 글자" 같은 타입 표시를 더한 언어예요. 실수를 코드 실행 전에 미리 잡아 주는 것이 가장 큰 장점입니다. 예를 들어 숫자 자리에 실수로 글자를 넣으면, JavaScript는 실행해 봐야 알지만 TypeScript는 코드를 적는 순간 바로 알려줍니다. 🔷',
    body: [
      '예를 들어 숫자가 들어와야 할 자리에 실수로 글자를 넣으면, JavaScript는 실행해 봐야 문제를 알 수 있지만 TypeScript는 코드를 적는 순간 바로 알려줍니다.',
      '실무에서는 React·Next.js 프로젝트 대부분이 이 언어로 작성됩니다. AI 코딩 도구도 요즘은 기본값으로 TypeScript 코드를 만들어 주는 경우가 많습니다.',
    ],
    note: '문법이 하나 더 늘어난 것처럼 보여도, 결국 실행될 때는 다시 JavaScript로 변환됩니다. "안전장치가 붙은 JavaScript" 정도로 이해하면 충분합니다.',
    related: ['javascript', 'react', 'nextjs'],
  },
  {
    id: 'react',
    emoji: '⚛️',
    term: 'React',
    en: 'react.dev · Meta',
    part: 'part02',
    kind: 'tool',
    short: '버튼, 카드, 메뉴처럼 화면의 작은 조각(컴포넌트)을 레고 블록처럼 조립해서 웹 화면을 만드는 JavaScript 라이브러리예요. "프로필 카드"를 한 번 만들어 두면, 그 조각을 여러 번 재사용해서 목록 전체를 채울 수 있습니다. 지금 가장 널리 쓰이는 화면 제작 도구입니다. ⚛️',
    body: [
      '"프로필 카드"를 한 번 만들어 두면, 그 조각을 여러 번 재사용해서 목록 전체를 채울 수 있습니다. 화면 하나하나를 처음부터 다시 짜지 않아도 되는 것이 핵심이에요.',
      'V0 같은 도구가 뽑아 주는 코드도 대부분 React 형태입니다. React의 기본 개념(컴포넌트, 조각을 조립한다는 것)만 알아도 AI가 만들어 준 코드를 훨씬 편하게 읽을 수 있습니다.',
    ],
    related: ['javascript', 'nextjs', 'v0', 'react-native'],
  },
  {
    id: 'react-native',
    emoji: '📱',
    term: 'React Native',
    en: 'Meta · JavaScript',
    part: 'part02',
    kind: 'tool',
    short: '메타(옛 페이스북)가 만든 크로스플랫폼 앱 개발 도구예요. 이 과정에서 배우는 React와 같은 문법으로 코드를 짜되, 화면은 웹이 아니라 진짜 아이폰·안드로이드 네이티브 화면 요소로 그려 줍니다. 📱',
    body: [
      'React를 웹이 아니라 <strong>모바일 앱</strong>에 쓸 수 있게 만든 프레임워크입니다. 컴포넌트를 만드는 방식이 React와 비슷해서, 웹을 React로 배운 사람이 넘어가기 비교적 수월합니다.',
      '실습이나 빠른 시작에는 <strong>Expo</strong>라는 도구를 함께 쓰는 경우가 많습니다. 복잡한 네이티브 설정 없이도 앱을 실행하고 미리보기까지 해 볼 수 있게 도와줍니다.',
    ],
    spectrum: { leftLabel: '설치 없이 브라우저에서 바로 씀', rightLabel: '스토어에서 설치하는 진짜 앱', value: 85 },
    related: ['react', 'cross-platform', 'flutter', 'app-store-deploy'],
  },
  {
    id: 'flutter',
    emoji: '🦋',
    term: 'Flutter',
    en: 'Google · Dart',
    part: 'part02',
    kind: 'tool',
    short: '구글이 만든 크로스플랫폼 앱 개발 도구예요. Dart라는 언어로 한 번 코드를 짜면 아이폰·안드로이드 앱을 동시에 만들어 주고, 화면을 직접 그리는 방식이라 기기가 달라도 디자인이 거의 똑같이 보이는 것이 특징입니다. 🦋',
    body: [
      '버튼이나 글자 같은 화면 요소를 운영체제에서 빌려 쓰지 않고 <strong>Flutter가 직접 화면에 그립니다.</strong> 그래서 아이폰에서 보든 안드로이드에서 보든 디자인이 거의 똑같이 나온다는 장점이 있습니다.',
      '구글의 실험용 프로젝트로 2017년 알파 버전이 처음 공개됐고, 2018년 12월 정식(1.0) 버전이 나온 뒤로 알리바바·바이트댄스 같은 큰 회사의 앱에도 쓰일 만큼 자리를 잡았습니다.',
    ],
    spectrum: { leftLabel: '설치 없이 브라우저에서 바로 씀', rightLabel: '스토어에서 설치하는 진짜 앱', value: 90 },
    related: ['cross-platform', 'react-native', 'app-store-deploy'],
  },
  {
    id: 'cross-platform',
    emoji: '📲',
    term: '크로스플랫폼 개발',
    en: 'Cross-platform Development',
    part: 'part02',
    kind: 'concept',
    short: '하나의 코드로 iOS와 Android 앱을 동시에 만드는 개발 방식이에요. 원래는 아이폰용 따로, 안드로이드용 따로 각각 다른 언어로 두 번 만들어야 했는데, Flutter나 React Native 같은 도구가 이 수고를 크게 줄여 줍니다. 🧩',
    body: [
      '아이폰 앱은 Swift, 안드로이드 앱은 Kotlin처럼 원래는 플랫폼마다 다른 언어·도구로 따로 개발해야 했습니다. 크로스플랫폼 도구는 하나의 코드베이스를 양쪽 스토어용 앱으로 각각 빌드해 줘서 개발 시간과 유지보수 부담을 줄여 줍니다.',
      '다만 카메라나 센서처럼 운영체제 깊숙한 기능을 쓸 때는 플랫폼별로 추가 설정이 필요하기도 하고, 완전 네이티브 앱보다 미묘하게 느리거나 어색하게 동작하는 부분이 생길 수 있습니다.',
    ],
    flow: 'flowchart LR\n' +
          'A["하나의 코드베이스"] --> B["iOS 앱"]\n' +
          'A --> C["Android 앱"]',
    related: ['flutter', 'react-native', 'pwa'],
  },
  {
    id: 'pwa',
    emoji: '📌',
    term: 'PWA',
    en: 'Progressive Web App',
    part: 'part02',
    kind: 'concept',
    short: '앱스토어를 거치지 않고, 웹사이트를 스마트폰 홈 화면에 아이콘으로 "설치"해서 앱처럼 쓸 수 있게 만드는 기술이에요. 브라우저 주소창 없이 전체 화면으로 뜨고, 오프라인에서도 어느 정도 동작하게 만들 수 있습니다. 📌',
    body: [
      'GitHub Pages처럼 그냥 웹으로 배포한 페이지에 몇 가지 설정을 더하면, 사용자가 "홈 화면에 추가"를 눌러 앱처럼 아이콘을 만들 수 있습니다. 심사를 기다릴 필요도, 스토어 등록비도 없습니다.',
      '다만 카메라·푸시 알림·백그라운드 실행처럼 운영체제 깊숙한 기능은 Flutter·React Native로 만든 진짜 앱보다 제약이 많습니다. "빠르게 앱처럼 보여 주고 싶다"에는 좋지만, 본격적인 앱 기능이 필요하면 크로스플랫폼 도구로 넘어가는 편이 낫습니다.',
    ],
    spectrum: { leftLabel: '설치 없이 브라우저에서 바로 씀', rightLabel: '스토어에서 설치하는 진짜 앱', value: 15 },
    related: ['github-pages', 'cross-platform', 'flutter', 'react-native'],
  },
  {
    id: 'app-store-deploy',
    emoji: '🏪',
    term: '앱스토어 배포',
    en: 'App Store · Google Play',
    part: 'part02',
    kind: 'deploy',
    short: '만든 모바일 앱을 애플 App Store나 구글 Play 스토어에 올려서 누구나 내려받을 수 있게 만드는 과정이에요. 웹사이트처럼 파일만 올리면 끝나는 게 아니라, 각 스토어의 심사를 통과해야 하고 몇 시간에서 며칠까지 걸릴 수 있습니다. 🏪',
    body: [
      '아이폰용 앱은 Mac에서 애플 공식 도구인 <strong>Xcode</strong>로 최종 빌드하고 서명해야 스토어에 올릴 수 있습니다. Flutter나 React Native로 코드를 짰더라도, iOS로 내보내는 마지막 단계에서는 결국 Mac과 Xcode가 필요합니다.',
      '안드로이드는 <strong>Android Studio</strong>(또는 커맨드라인 빌드 도구)로 빌드한 파일을 Google Play Console에 올립니다. 애플보다는 심사가 상대적으로 빠른 편이지만, 두 스토어 모두 개발자 계정 등록비와 심사 가이드라인 준수가 필요합니다.',
    ],
    note: '심사에서 거절되면 사유를 고치고 다시 제출해야 해서, 처음 배포할 때는 여유 있게 일정을 잡는 편이 안전합니다.',
    related: ['flutter', 'react-native', 'cross-platform'],
  },
  {
    id: 'txt',
    emoji: '📃',
    term: 'TXT',
    en: 'Plain Text',
    part: 'part02',
    kind: 'concept',
    short: '글자만 담고 있는 가장 단순한 파일 형식이에요. 글꼴이나 색깔 같은 꾸밈 정보가 전혀 없어서 어떤 프로그램으로 열어도 항상 같은 내용이 보입니다. requirements.txt처럼 설정 파일에도 자주 쓰입니다. 📃',
    body: [
      '워드나 한글 파일과 달리 "꾸밈"이 아예 없어서 용량이 아주 작고, 어떤 운영체제·프로그램에서 열어도 깨지지 않습니다. 그만큼 git으로 변경 내역을 비교하기에도 편합니다.',
      '이 과정에서는 requirements.txt(파이썬 패키지 목록), robots.txt(크롤링 허용 범위)처럼 설정용 파일 이름 끝에 자주 붙어 있는 걸 보게 됩니다.',
    ],
    related: ['md', 'json'],
  },
  {
    id: 'md',
    emoji: '📝',
    term: 'Markdown (MD)',
    en: '.md',
    part: 'part02',
    kind: 'concept',
    short: '별표(*)나 우물 정(#) 같은 간단한 기호로 제목·굵게·목록 같은 서식을 표현하는 글쓰기 형식이에요. GitHub의 README.md, 이 용어사전의 설명 글도 전부 마크다운으로 되어 있습니다. 📝',
    body: [
      '# 제목, **굵게**, - 목록처럼 몇 가지 기호만 외우면 워드 프로그램 없이도 문서 구조를 잡을 수 있습니다. GitHub·Notion 같은 서비스가 이 문법을 자동으로 예쁜 화면으로 바꿔서 보여 줍니다.',
      '프로젝트 저장소에 넣는 <strong>README.md</strong>가 대표적인 예입니다. "이 프로젝트가 뭐고 어떻게 쓰는지"를 설명하는 첫 페이지 역할을 합니다.',
    ],
    related: ['github', 'txt'],
  },
  {
    id: 'json',
    emoji: '🧾',
    term: 'JSON',
    en: 'JavaScript Object Notation',
    part: 'part02',
    kind: 'concept',
    short: '{"이름": "값"} 형태로 데이터를 정리해서 담는 파일 형식이에요. 사람도 읽을 수 있을 만큼 단순하면서 프로그램이 다루기도 쉬워서, API가 데이터를 주고받을 때 사실상 표준으로 쓰입니다. 🧾',
    body: [
      '중괄호 {}와 콜론(:)으로 "키: 값" 쌍을 나열하는 방식이라, 표(CSV)로 담기 애매한 중첩 구조(목록 안에 목록처럼)도 자연스럽게 표현할 수 있습니다.',
      '이 과정에서 쓰는 도구 대부분이 뒤에서 JSON을 주고받습니다. AI에게 API 요청을 보내면 답도 JSON으로 오고, 웹앱의 설정 파일(package.json)도 JSON 형식입니다.',
    ],
    flow: 'flowchart LR\n' +
          'A["API 요청"] --> B["JSON 응답"]\n' +
          'B --> C["표 형태로 정리"]\n' +
          'C --> D["CSV·엑셀로 저장"]',
    related: ['csv', 'api', 'javascript'],
  },
  {
    id: 'env',
    emoji: '🔑',
    term: '.env 파일',
    en: 'Environment Variables',
    part: 'part02',
    kind: 'concept',
    short: 'API 키나 비밀번호처럼 남에게 보이면 안 되는 값을 코드와 분리해서 담아 두는 파일이에요. 코드에는 "이 값을 .env에서 가져와 써라"라고만 적어 두고, 진짜 값은 이 파일 하나에만 둡니다. 🔑',
    body: [
      '코드 안에 API 키를 직접 적어 두면, 그 코드를 GitHub에 올리는 순간 키가 그대로 공개돼 버립니다. .env 파일에 값을 따로 두고 코드에서 불러다 쓰면 이런 사고를 막을 수 있습니다.',
      '그래서 <strong>.gitignore</strong>에 반드시 .env를 추가해서 실수로 커밋되지 않게 막아야 합니다. 대신 어떤 값이 필요한지 알려 주는 .env.example 파일만 저장소에 올려 둡니다.',
    ],
    note: '이미 GitHub에 올려서 공개된 적이 있는 키는, .env로 옮기는 것만으로는 안전하지 않습니다 — 반드시 키를 새로 발급받아야 합니다. ⚠️',
    related: ['gitignore', 'github'],
  },
  {
    id: 'gitignore',
    emoji: '🚫',
    term: '.gitignore',
    en: 'git',
    part: 'part02',
    kind: 'concept',
    short: 'git이 절대 추적하거나 GitHub에 올리지 않아야 할 파일·폴더 목록을 적어 두는 특수 파일이에요. .env, node_modules/, .DS_Store처럼 비밀값이거나 용량만 크고 굳이 공유할 필요 없는 것들을 여기에 적어 둡니다. 🚫',
    body: [
      '이 파일에 이름을 적어 두면 git status나 git add에 아예 나타나지 않아서, 실수로 커밋하는 사고를 원천적으로 막아 줍니다. 프로젝트를 시작할 때(git init 직후) 가장 먼저 만들어 두는 습관이 좋습니다.',
      '이미 한 번 커밋된 파일은 나중에 .gitignore에 추가해도 계속 추적됩니다. 그 경우 git rm --cached로 추적만 따로 해제해야 합니다.',
    ],
    related: ['env', 'git-commit-cycle', 'github'],
  },
  {
    id: 'nextjs',
    emoji: '⏭️',
    term: 'Next.js',
    en: 'nextjs.org · Vercel',
    part: 'part02',
    kind: 'tool',
    short: 'React만으로는 손이 많이 가는 부분(페이지 이동, 서버 쪽 처리, 배포 최적화 등)을 미리 갖춰 둔 React 프레임워크예요. Vercel이 만들고 관리하며, 그만큼 Vercel에 올릴 때 가장 매끄럽게 동작합니다. React가 화면 조각을 만드는 법이라면, Next.js는 그 조각들을 모아 서비스 하나로 완성하는 나머지 부분까지 갖춰 줍니다. ⏭️',
    body: [
      'React가 "화면 조각을 만드는 법"을 알려준다면, Next.js는 그 조각들을 모아 실제 서비스 하나로 완성하는 데 필요한 나머지 부분(주소 체계, 데이터 불러오기, 배포)까지 갖춘 상태로 시작하게 해 줍니다.',
      '만든 회사인 Vercel에 올리면 별다른 설정 없이 가장 잘 맞게 배포됩니다. <strong>Vercel</strong> 카드와 함께 보면 왜 둘이 자주 같이 언급되는지 이해가 쉽습니다.',
    ],
    related: ['react', 'vercel', 'typescript'],
  },
  {
    id: 'tailwind-css',
    emoji: '🌬️',
    term: 'Tailwind CSS',
    en: 'tailwindcss.com',
    part: 'part02',
    kind: 'tool',
    short: 'CSS를 직접 한 줄씩 짜는 대신, 미리 정해진 짧은 이름(클래스)을 HTML에 붙이기만 하면 스타일이 적용되는 도구예요. "여백은 이만큼, 글씨는 파란색" 같은 걸 이름표처럼 붙입니다. 예를 들어 text-blue-500 하나만 붙이면 글씨가 파란색이 됩니다. 🌬️',
    body: [
      '예를 들어 <code>text-blue-500</code>이라는 이름표 하나만 붙이면 글씨가 파란색이 됩니다. CSS 파일을 따로 열어 규칙을 적을 필요 없이, HTML 안에서 바로 꾸밀 수 있어요.',
      'V0 같은 AI 도구가 뽑아 주는 화면 코드 대부분이 이 방식으로 스타일을 입힙니다. 코드를 열었을 때 낯선 짧은 단어들이 잔뜩 붙어 있다면 대부분 Tailwind 클래스입니다.',
    ],
    related: ['css', 'v0', 'shadcn-ui'],
  },
  {
    id: 'shadcn-ui',
    emoji: '🧩',
    term: 'shadcn/ui',
    en: 'ui.shadcn.com',
    part: 'part02',
    kind: 'tool',
    short: '버튼, 입력창, 팝업창처럼 자주 쓰는 화면 부품을 미리 예쁘게 만들어 둔 컴포넌트 모음이에요. 필요한 것만 골라 내 프로젝트에 복사해서 씁니다. 통째로 설치하는 라이브러리가 아니라 코드를 그대로 가져오는 방식이라, 나중에 마음대로 고쳐도 다른 프로젝트에 영향이 없습니다. 🧩',
    body: [
      '다른 도구들처럼 통째로 설치하는 라이브러리가 아니라, 필요한 컴포넌트의 <strong>코드를 그대로 내 프로젝트에 복사해 오는</strong> 방식입니다. 그래서 나중에 마음대로 고쳐도 다른 프로젝트에 영향이 없습니다.',
      'React + Tailwind CSS 조합 위에서 동작합니다. V0가 뽑아 주는 화면 코드에도 이 컴포넌트들이 자주 섞여 있습니다.',
    ],
    related: ['react', 'tailwind-css', 'v0'],
  },
  {
    id: 'claude-code',
    emoji: '💻',
    term: 'Claude Code',
    en: 'Anthropic',
    part: 'part02',
    kind: 'tool',
    short: '터미널에서 대화하듯 시키면 파일을 직접 읽고, 고치고, 실행까지 해 주는 AI 코딩 도구예요. "로그인 기능이 안 되는데 고쳐 줘"처럼 말하면 관련 파일을 스스로 찾아 고친 뒤 잘 되는지까지 확인합니다. 사전 학습에서 터미널 영상을 먼저 보라고 하는 이유가 바로 이 도구 때문입니다. ⌨️',
    body: [
      '"로그인 기능이 안 되는데 원인을 찾아서 고쳐 줘"라고 하면, 관련 파일을 스스로 찾아 읽고 고친 뒤 잘 되는지까지 확인합니다. 답만 알려 주는 것이 아니라 <strong>일을 해 준다</strong>는 점이 다릅니다.',
      '그래서 AI 에이전트의 대표적인 예이기도 합니다. 무엇을 허용할지 사용자가 정할 수 있게 되어 있어요.',
    ],
    related: ['codex', 'ai-agent', 'vibe-coding', 'vscode', 'cmux', 'sub-agent', 'claude'],
  },
  {
    id: 'codex',
    emoji: '🧰',
    term: 'Codex',
    en: 'OpenAI',
    part: 'part02',
    kind: 'tool',
    short: 'ChatGPT를 만든 OpenAI의 AI 코딩 도구예요. 마찬가지로 "이 기능 만들어 줘"라고 시키면 코드를 쓰고 고쳐 줍니다. Claude Code와 성격이 비슷해서, 수업에서 같은 과제를 두 도구에 시켜 보고 결과를 비교해 봅니다. ⚖️',
    body: [
      '어느 쪽이 정답이라기보다 손에 맞는 도구가 다릅니다. 같은 과제를 두 도구에 시켜 보고 결과와 사용감을 비교하는 것도 좋은 연습이에요.',
      'AI 코딩 도구는 계속 새로 나오고 이름도 자주 바뀝니다. 도구 이름을 외우기보다 <strong>시키는 방법</strong>을 익히면 새 도구가 나와도 금방 적응할 수 있습니다.',
    ],
    related: ['claude-code', 'vibe-coding', 'chatgpt'],
  },
  {
    id: 'vscode',
    emoji: '🟦',
    term: 'Visual Studio Code',
    en: 'VS Code · Microsoft',
    part: 'part02',
    kind: 'tool',
    short: '코드를 작성·수정할 때 쓰는 무료 코드 편집기예요. 문법 강조, 자동완성 같은 기능을 갖추고 있어서 지금 가장 널리 쓰이는 개발 도구 중 하나입니다. 메모장과 달리 코드를 "이해하고" 오타나 실수를 미리 잡아 주는 것이 특징입니다. 🟦',
    body: [
      '메모장과 다른 점은 코드를 "이해하고" 도와준다는 것입니다. 오타를 미리 잡아 주고, 함수 이름을 치다 말면 자동으로 완성해 주고, 관련된 코드로 바로 이동할 수 있게 해 줍니다.',
      'Claude Code 같은 터미널 기반 AI 도구와 함께 쓸 때는, VS Code 안에 터미널 창을 띄워 두고 그 안에서 AI에게 작업을 시키는 방식이 흔합니다.',
    ],
    related: ['claude-code', 'javascript', 'html'],
  },
  {
    id: 'cmux',
    emoji: '🖥️',
    term: 'cmux',
    en: 'cmux.dev',
    part: 'part02',
    kind: 'tool',
    short: '터미널에서 Claude Code, Codex 같은 AI 코딩 에이전트 여러 개를 동시에 켜 두고 나란히 지켜볼 수 있게 만든 macOS 전용 터미널이에요. 에이전트마다 탭을 하나씩 배정해서, 어느 쪽이 끝났는지 알림으로 확인할 수 있습니다. 화면 안에 브라우저 창도 함께 띄울 수 있어서 결과를 바로 확인시킬 수도 있습니다. 🖥️',
    body: [
      '에이전트를 하나씩 실행하고 화면을 왔다갔다하는 대신, 여러 개를 동시에 돌리면서 어느 쪽이 끝났는지 알림으로 확인할 수 있습니다. 화면 안에 브라우저 창도 함께 띄울 수 있어서, 에이전트가 만든 결과를 바로 확인시킬 수도 있습니다.',
      '이름의 "mux"는 여러 개를 하나로 묶어 다룬다는 뜻의 멀티플렉서(multiplexer)에서 왔습니다. 개발자들이 오래 써온 <code>tmux</code>라는 터미널 도구의 계보를 잇는 이름이에요.',
    ],
    note: '아직 macOS 전용 도구입니다. Windows에서 비슷한 걸 쓰고 싶다면 <strong>wmux</strong>를 참고합니다.',
    related: ['claude-code', 'codex', 'ai-agent', 'wmux'],
  },
  {
    id: 'wmux',
    emoji: '🪟',
    term: 'wmux',
    en: 'Windows',
    part: 'part02',
    kind: 'tool',
    short: 'cmux의 Windows 버전 격인 터미널 도구예요. WSL 없이도 Claude Code·Codex·Gemini CLI 같은 AI 에이전트 여러 개를 창 하나에서 나눠서 동시에 돌릴 수 있습니다. 재미있게도 이 도구 자체가 Claude Code로 개발됐다고 알려져 있습니다. 🪟',
    body: [
      'Windows에는 원래 tmux 같은 터미널 다중화 도구가 기본으로 없어서, 리눅스용 도구를 쓰려면 WSL(Windows용 리눅스)을 거쳐야 했습니다. wmux는 그 과정 없이 Windows에서 곧바로 여러 에이전트를 나눠서 돌릴 수 있게 만든 도구입니다.',
      '이 도구 자체가 Claude Code로 개발됐다고 알려져 있습니다 — AI 코딩 도구가 AI 코딩 도구를 위한 도구를 만든 사례인 셈입니다.',
    ],
    related: ['cmux', 'claude-code', 'codex'],
  },
  {
    id: 'antigravity',
    emoji: '🛸',
    term: 'Antigravity',
    en: 'Google',
    part: 'part02',
    kind: 'tool',
    short: '구글이 만든, AI 코딩 에이전트가 기본으로 내장된 코드 에디터(IDE)예요. VS Code처럼 코드를 편집하는 화면이지만, 그 안에 Claude Code 같은 AI 에이전트가 처음부터 통합되어 있다는 점이 다릅니다. 2025년 말에 공개된 비교적 신생 도구예요. 🛸',
    body: [
      'VS Code 같은 기존 에디터에서는 AI 에이전트를 터미널이나 확장 프로그램으로 따로 붙여서 씁니다. Antigravity는 반대로 <strong>에디터 자체에 AI 에이전트가 기본 탑재</strong>되어 있어서, 코드를 고치고 실행하고 확인하는 과정을 에디터 안에서 곧바로 이어갈 수 있습니다.',
      '구글이 2025년 말에 내놓은 만큼 아직 역사는 짧지만, "에디터 안에 에이전트가 원래부터 있다"는 방향이 앞으로 다른 도구들에도 번질 가능성이 있는 시도로 꼽힙니다.',
    ],
    note: '아직 나온 지 얼마 되지 않은 도구라 기능과 화면 구성이 빠르게 바뀔 수 있습니다. 🌱',
    related: ['claude-code', 'vscode', 'vibe-coding'],
  },
  {
    id: 'streamlit',
    emoji: '🎈',
    term: 'Streamlit',
    en: 'streamlit.io',
    part: 'part02',
    kind: 'tool',
    short: '파이썬 코드 몇 줄만으로 버튼·입력창 같은 화면을 가진 웹앱을 만들어 주는 프레임워크예요. HTML·CSS를 몰라도 데이터 분석가나 AI 개발자가 결과를 웹 화면으로 빠르게 보여줄 때 씁니다. 챗봇처럼 대화하는 화면을 만드는 데도 자주 쓰입니다. 🎈',
    body: [
      '데이터를 분석한 결과나 만든 모델을 남에게 보여 주려면 보통 화면(웹앱)이 필요한데, HTML·CSS·JavaScript를 배우려면 시간이 걸립니다. Streamlit은 <strong>파이썬 코드만으로</strong> 버튼, 슬라이더, 입력창 같은 화면 요소를 만들 수 있게 해서 이 과정을 건너뛰게 해 줍니다.',
      '채팅 입력창과 대화 내용을 보여 주는 부품을 기본으로 갖추고 있어서, <strong>챗봇 UI</strong>를 만드는 데도 특히 자주 쓰입니다. 이 과정 5회차 산출물인 "Claude Code 자동화 프로그램 + Streamlit 챗봇 배포"도 이 도구로 화면을 만듭니다.',
    ],
    related: ['python', 'claude-code', 'antigravity'],
  },
  {
    id: 'electron',
    emoji: '📦',
    logo: 'logos/electron.svg',
    term: 'Electron',
    en: 'electronjs.org',
    part: 'part02',
    kind: 'tool',
    short: 'HTML·CSS·JS로 만든 웹 화면을 그대로 감싸서, 윈도우·맥에 설치하는 진짜 데스크톱 앱으로 만들어 주는 도구예요. VS Code, Slack, Discord 같은 유명 프로그램도 이걸로 만들어졌습니다. 웹페이지를 만들 줄 알면 데스크톱 앱을 위한 언어를 새로 배우지 않아도 되는 것이 가장 큰 장점입니다. 🖥️',
    body: [
      '웹페이지를 만들 줄 알면 데스크톱 앱을 위한 언어를 새로 배우지 않아도 됩니다. 브라우저 엔진(Chromium)을 앱 안에 통째로 넣어서, 같은 웹 코드가 어느 컴퓨터에서나 똑같이 돌아가게 해 주기 때문이에요.',
      '그 대신 앱 하나마다 브라우저 엔진을 함께 담고 다니기 때문에 설치 파일 용량이 크고 메모리를 많이 씁니다. 가볍게 만들고 싶다는 요구가 생기면 <strong>Tauri</strong> 같은 대안을 함께 고려합니다.',
    ],
    note: 'GitHub Pages는 "웹 주소로 열어 보는" 방식이고, Electron은 "설치해서 쓰는 프로그램"으로 만드는 방식이에요. 오프라인에서도 써야 하거나 파일 시스템에 직접 접근해야 하는 앱이라면 Electron 쪽을 고려합니다. 💾',
    spectrum: { leftLabel: '가벼움', rightLabel: '무거움', value: 80 },
    related: ['tauri', 'html', 'vibe-coding'],
  },
  {
    id: 'tauri',
    emoji: '🦀',
    term: 'Tauri',
    en: 'tauri.app',
    part: 'part02',
    kind: 'tool',
    short: 'Electron과 목적은 같지만(웹 코드로 데스크톱 앱 만들기), 브라우저 엔진을 따로 담지 않고 운영체제에 이미 있는 웹뷰(운영체제에 내장된, 웹페이지를 보여주는 부품)를 빌려 써서 설치 파일이 훨씬 작고 가벼운 도구예요. 뒷단은 속도와 안전성으로 유명한 Rust라는 언어로 짜여 있어서, 파일 접근처럼 시스템과 맞닿는 부분도 안정적으로 처리합니다. "가볍고 빠른 데스크톱 앱"을 목표로 할 때 특히 많이 비교되는 도구예요. 🪶',
    body: [
      '화면(프론트엔드, 사용자 눈에 보이는 부분)은 Electron과 똑같이 HTML·CSS·JS로 만듭니다. 다만 뒷단(백엔드, 눈에 안 보이는 처리 부분)은 속도와 안전성으로 유명한 <strong>Rust</strong>라는 언어로 되어 있어서, 파일 접근처럼 시스템과 맞닿는 부분을 더 빠르고 안전하게 처리합니다. 1Password 같은 앱의 최신 버전이 이 방식으로 만들어졌습니다.',
      'Electron보다 역사가 짧아서 참고할 자료나 라이브러리는 아직 상대적으로 적지만, 2024년 나온 Tauri 2 버전부터는 아이폰·안드로이드 앱까지 만들 수 있을 정도로 빠르게 성장하고 있습니다. "일단 빨리 만들어 본다"에는 Electron, "가볍고 빠른 완성형을 노린다"에는 Tauri를 저울질해 보면 좋습니다.',
    ],
    spectrum: { leftLabel: '가벼움', rightLabel: '무거움', value: 20 },
    related: ['electron', 'vibe-coding'],
  },
  {
    id: 'git-commit-cycle',
    emoji: '💾',
    term: '커밋 사이클',
    en: 'status · add · commit · push',
    part: 'part02',
    kind: 'concept',
    short: '코드를 고친 뒤 그 변경을 기록하고 GitHub에 올리기까지 반복하는 4단계예요. status로 무엇이 바뀌었는지 보고, add로 올릴 파일을 고르고(stage), commit으로 하나의 저장 지점(스냅샷)을 만들고, push로 GitHub에 업로드합니다. 이 네 걸음은 프로젝트를 만드는 내내 계속 반복됩니다. 💾',
    body: [
      '작업 폴더에서 파일을 고치는 것만으로는 아무 기록도 남지 않습니다. <code>git status</code>로 무엇이 달라졌는지 먼저 확인하는 습관이 실수를 줄여 줍니다.',
      '<code>git add</code>는 "이번 저장에 이 파일을 포함할래"라고 고르는 단계이고, <code>git commit</code>은 고른 파일들을 하나의 저장 지점으로 굳히는 단계입니다. 커밋 메시지에는 무엇을·왜 바꿨는지 짧게 남겨 둡니다.',
      '<code>git push</code>를 해야 로컬 컴퓨터의 기록이 실제로 GitHub 원격 저장소에 올라갑니다. push하지 않은 commit은 내 컴퓨터에만 있는 상태입니다.',
    ],
    note: 'commit 전에 <code>git diff --cached</code>로 실제로 무엇이 올라가는지 한 번 더 확인하는 편이 안전합니다.',
    related: ['github', 'git-branch', 'git-merge'],
  },
  {
    id: 'git-branch',
    emoji: '🌿',
    term: '브랜치',
    en: 'git branch',
    part: 'part02',
    kind: 'concept',
    short: '원본 코드(main)를 건드리지 않고 독립된 작업 공간을 만드는 기능이에요. 새 기능을 시도하다 실패해도 main은 그대로 안전하고, 성공하면 나중에 합치면(merge) 됩니다. 여러 사람이 동시에 각자 다른 기능을 작업할 때도 서로 부딪히지 않게 해 줍니다. 🌿',
    body: [
      '<code>git branch feature/login</code>으로 새 브랜치를 만들고 <code>git switch feature/login</code>으로 이동합니다. 이 브랜치 안에서 무엇을 바꾸든 main에는 영향이 없습니다.',
      '작업이 끝나면 main으로 돌아가 <code>git merge</code>로 합칩니다. 실패한 시도는 그냥 브랜치를 지우면(<code>git branch -d</code>) main에는 흔적조차 남지 않습니다.',
    ],
    note: '기능 하나당 브랜치 하나가 기본 습관입니다. main에서 바로 작업하다 실수하면 되돌리기가 훨씬 번거롭습니다.',
    related: ['git-fetch', 'git-merge', 'git-commit-cycle', 'github'],
  },
  {
    id: 'git-fetch',
    emoji: '📥',
    term: 'Fetch',
    en: 'git fetch',
    part: 'part02',
    kind: 'concept',
    short: '원격 저장소(GitHub)에 쌓인 새 변경 내역을 내 컴퓨터로 받아만 오고, 내 작업 브랜치에는 아직 합치지 않는 명령이에요. 팀원이 push한 내용이 있는지 안전하게 미리 확인하고 싶을 때 씁니다. 📥',
    body: [
      '<code>git fetch origin</code>을 실행하면 원격의 최신 기록이 <code>origin/main</code>처럼 별도 이름으로 내려옵니다. 내가 지금 보고 있는 파일은 바뀌지 않습니다.',
      '많이 쓰는 <code>git pull</code>은 사실 <code>fetch</code>와 <code>merge</code>를 한 번에 실행하는 단축 명령입니다. 무엇이 바뀌었는지 먼저 보고 싶다면 fetch를 따로 쓰는 편이 안전합니다.',
    ],
    related: ['git-branch', 'git-merge', 'git-commit-cycle', 'github'],
  },
  {
    id: 'git-merge',
    emoji: '🔀',
    term: 'Merge',
    en: 'git merge',
    part: 'part02',
    kind: 'concept',
    short: '다른 브랜치에서 작업한 변경 내역을 지금 있는 브랜치로 합치는 명령이에요. 두 브랜치가 서로 다른 부분을 고쳤다면 자동으로 합쳐지지만, 같은 부분을 다르게 고쳤다면 "충돌(conflict)"이 나서 직접 골라 줘야 합니다. 🔀',
    body: [
      '내가 있는 브랜치(main)에 그동안 새 commit이 없었다면, Git은 브랜치 표시를 앞으로 옮기기만 하는 <strong>fast-forward merge</strong>로 조용히 끝냅니다. 반면 main에도 다른 commit이 쌓여 있었다면, 두 브랜치가 겹치지 않는 부분을 고쳤을 때 Git이 자동으로 병합 commit을 만들어 줍니다(3-way merge).',
      '같은 파일의 같은 줄을 두 브랜치가 다르게 고쳤을 때는 이 자동 병합이 실패하고 충돌이 납니다. 파일을 열어 <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code>·<code>=======</code>·<code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code> 표시 사이에서 남길 내용을 고른 뒤 다시 commit하면 됩니다.',
    ],
    note: '막막하면 <code>git merge --abort</code>로 merge 시도 자체를 취소하고 이전 상태로 돌아갈 수 있습니다.',
    related: ['git-branch', 'git-fetch', 'git-commit-cycle', 'github'],
  },

  /* ---- PART 03. UX/UI 디자인 ---- */
  {
    id: 'ux',
    emoji: '🙂',
    term: 'UX',
    en: 'User Experience · 사용자 경험',
    part: 'part03',
    kind: 'concept',
    short: '사용자가 제품을 쓰면서 느끼는 모든 것을 뜻해요. 앱을 처음 켠 순간부터 가입하고, 원하는 걸 찾고, 문제를 해결하기까지 전부 포함됩니다. "이거 왠지 쓰기 편하네" 하는 그 느낌, 반대로 "왜 이렇게 불편하지" 하는 짜증까지 모두 UX예요. 👍',
    body: [
      '배달 앱으로 예를 들어 볼게요. 버튼 색이 예쁜 것만 UX가 아닙니다. 주문까지 몇 번을 눌러야 하는지, 배달이 언제 오는지 바로 알 수 있는지, 잘못 눌렀을 때 되돌릴 수 있는지가 모두 UX입니다.',
      '그래서 UX를 다룰 때는 화면 그림보다 먼저 <strong>사용자가 무엇을 하려고 왔는지</strong>를 생각합니다. 흐름, 구조, 문구, 속도가 전부 UX의 재료입니다.',
    ],
    flow: 'flowchart TD\n' +
          'subgraph UX["UX · 사용자 경험 (여정 전체)"]\n' +
          '  UI["UI · 사용자 인터페이스 (화면 요소)"]\n' +
          'end',
    related: ['ui'],
  },
  {
    id: 'ui',
    emoji: '🎨',
    term: 'UI',
    en: 'User Interface · 사용자 인터페이스',
    part: 'part03',
    kind: 'concept',
    short: '화면에서 눈에 보이고 손으로 누르는 것들이에요. 버튼, 입력창, 색깔, 글씨 크기, 여백 같은 것들이죠. UI는 UX를 이루는 한 부분이라서, UI가 예뻐도 UX는 나쁠 수 있고 반대의 경우도 있습니다. 🤔',
    body: [
      '"버튼이 참 예쁜데, 어디를 눌러야 다음으로 넘어가는지 모르겠는 화면"을 떠올려 보세요. UI는 훌륭한데 UX는 실패한 경우입니다.',
      '반대로 화려하지 않아도 누를 곳이 한눈에 보이고 글씨가 잘 읽히면 좋은 UI입니다. 수업에서는 <strong>보기 좋게</strong>와 <strong>쓰기 쉽게</strong>를 같이 만족시키는 연습을 합니다.',
    ],
    related: ['ux', 'figma'],
  },
  {
    id: 'figma',
    emoji: '🖌️',
    logo: 'logos/figma.svg',
    term: 'Figma',
    en: 'figma.com',
    part: 'part03',
    kind: 'tool',
    short: '웹사이트와 앱 화면을 그리는 디자인 도구예요. 설치 없이 브라우저에서 열리고, 여러 사람이 같은 화면을 동시에 보면서 작업할 수 있습니다. 디자이너뿐 아니라 기획자·개발자도 함께 들어가서 확인하는 자리로 쓰이는, 이 분야에서 사실상 표준 도구입니다. 👥',
    body: [
      '그림만 그리는 것이 아니라, 버튼을 누르면 다음 화면으로 넘어가는 것처럼 <strong>실제로 눌러지는 프로토타입</strong>까지 만들 수 있습니다.',
      '디자이너만 쓰는 도구가 아닙니다. 기획자와 개발자가 같은 화면을 함께 보며 "여기를 누르면 어디로 가나요?"를 확인하는 자리로 씁니다. 무료로 시작할 수 있어요.',
    ],
    related: ['ui', 'prototype'],
  },
  {
    id: 'png',
    emoji: '🖼️',
    term: 'PNG',
    en: 'Portable Network Graphics',
    part: 'part03',
    kind: 'concept',
    short: '화질 손실 없이 저장되고 투명한 배경도 지원하는 이미지 파일 형식이에요. 스크린샷, 로고, UI 디자인 시안처럼 "선명해야 하고 배경이 비쳐야 하는" 이미지에 주로 씁니다. 🖼️',
    body: [
      '압축을 해도 원본 그대로 복원되는 방식(무손실 압축)이라 글자나 아이콘처럼 선이 뚜렷한 이미지가 흐려지지 않습니다. 대신 사진처럼 색이 복잡한 이미지는 JPG보다 파일 용량이 커지는 편입니다.',
      '배경을 투명하게 저장할 수 있어서, 로고나 아이콘을 웹페이지 어디에 올려도 배경색과 자연스럽게 어울립니다. 이 교안들의 스크린샷도 대부분 PNG입니다.',
    ],
    related: ['jpg', 'figma'],
  },
  {
    id: 'jpg',
    emoji: '📷',
    term: 'JPG',
    en: 'JPEG',
    part: 'part03',
    kind: 'concept',
    short: '사진처럼 색이 다양한 이미지를 작은 용량으로 압축해서 저장하는 이미지 파일 형식이에요. 압축 과정에서 눈에 잘 안 띄는 정보를 버리기 때문에(손실 압축), 같은 사진이라도 PNG보다 파일이 훨씬 작습니다. 📷',
    body: [
      '압축률을 조절할 수 있어서 "화질은 살짝 포기하고 용량을 크게 줄이는" 선택이 가능합니다. 사진 위주의 웹페이지가 빨리 뜨게 하려고 사진은 보통 JPG로 씁니다.',
      '단, 투명 배경은 지원하지 않고 압축을 반복하면 화질이 점점 떨어집니다. 로고나 화면 캡처처럼 선명함이 중요하면 PNG를 쓰는 것이 낫습니다.',
    ],
    note: '"용량은 작게, 배경은 투명하게, 화질 저하도 없이"를 동시에 원한다면 이 둘 대신 WebP 같은 더 최신 형식을 고려해볼 수 있습니다.',
    related: ['png', 'figma'],
  },
  {
    id: 'prototype',
    emoji: '🧪',
    term: '프로토타입',
    en: 'Prototype · 시제품',
    part: 'part03',
    kind: 'concept',
    short: '완성품을 만들기 전에 "이렇게 동작할 거예요"를 미리 보여 주는 시제품이에요. 종이에 그린 그림부터 실제로 눌러지는 화면까지, 목적에 따라 정교함을 달리 만듭니다. 완성도보다 속도가 중요해서, 하루 만에 뚝딱 만들어 보고 버리는 경우도 흔합니다. ✅',
    body: [
      '말로만 설명하면 열 사람이 열 가지로 상상합니다. 프로토타입을 하나 만들어 놓으면 "아, 이런 거였구나" 하고 생각이 한곳으로 모여요.',
      '핵심은 <strong>완성도가 아니라 속도</strong>입니다. 빨리 만들어서 빨리 보여 주고, 반응을 보고 고치는 것이 목적입니다. 잘못된 방향을 일찍 발견할수록 손해가 적습니다.',
    ],
    related: ['figma', 'landing-page', 'lovable'],
  },
  {
    id: 'claude-design',
    emoji: '🪄',
    term: 'Claude Design',
    en: 'Anthropic',
    part: 'part03',
    kind: 'tool',
    short: 'Claude를 만든 회사 Anthropic이 내놓은 AI 디자인 도구예요. "카페 예약 앱의 홈 화면을 만들어 줘"처럼 말로 설명하면, 실제로 쓸 수 있는 화면 디자인 초안을 그려 줍니다. 자세히 설명할수록 원하는 모습에 가까운 결과가 나와요. 🪄',
    body: [
      '색깔·배치·구성 요소를 하나하나 손으로 그리는 대신, 원하는 화면을 문장으로 설명하면 <strong>디자인 초안</strong>이 통째로 만들어집니다. 마음에 안 드는 부분은 다시 말로 고쳐 나갈 수 있어요.',
      '아직 프로토타입이 없는 초반 단계에서, 화면의 전체적인 톤과 구성을 빠르게 잡아 보는 용도로 씁니다.',
    ],
    note: '이름이 비슷한 <strong>Claude Code</strong>와 헷갈리기 쉽습니다. Claude Code는 코드를 만드는 도구, Claude Design은 화면 디자인을 만드는 도구로 역할이 다릅니다. 🤝',
    related: ['claude-code', 'figma', 'figma-make', 'ui'],
  },
  {
    id: 'figma-make',
    emoji: '✨',
    term: 'Figma Make',
    en: 'figma.com',
    part: 'part03',
    kind: 'tool',
    short: 'Figma 안에서 말로 설명하면 AI가 화면 디자인 초안을 만들어 주는 기능이에요. "할 일 목록 앱의 메인 화면을 만들어 줘"처럼 요청하면, 그 자리에서 바로 편집할 수 있는 디자인이 생성됩니다. 백지에서 시작하기 막막할 때 첫 화면을 빠르게 띄워 주는 역할을 합니다. ✨',
    body: [
      '<strong>Figma</strong>라는 디자인 도구 안에 들어 있는 AI 생성 기능입니다. 도구를 새로 켤 필요 없이, 평소 쓰던 Figma 화면에서 그대로 요청하고 결과를 받아 볼 수 있어요.',
      '만들어진 결과는 일반 Figma 디자인과 똑같이 다루어집니다. 색깔을 바꾸거나 요소를 옮기는 것처럼, 손으로 직접 다듬어 완성도를 높이는 작업이 뒤따릅니다.',
    ],
    related: ['figma', 'claude-design', 'ui'],
  },
  {
    id: 'user-testing',
    emoji: '👀',
    term: '사용자 테스트',
    en: 'User Testing',
    part: 'part03',
    kind: 'concept',
    short: '만든 프로토타입을 실제 사용자에게 써 보게 하고, 어디서 헤매는지 어디가 불편한지 옆에서 지켜보는 활동이에요. 만든 사람 눈에는 당연해 보이는 것도, 처음 써 보는 사람에게는 전혀 다르게 보이는 경우가 많습니다. 말로 물어보는 것보다 직접 써 보게 하고 관찰하는 쪽이 훨씬 정확합니다. 👀',
    body: [
      '"이거 이해되세요?"라고 물으면 대부분 "네"라고 답합니다. 대신 실제로 화면을 눌러 보게 하고, 어디서 멈칫하는지 어디를 잘못 누르는지를 옆에서 조용히 지켜보는 쪽이 진짜 문제를 찾아냅니다.',
      '<strong>프로토타입</strong> 카드에서 말한 "빨리 만들어서 반응을 보고 고친다"의 그 "반응을 보는" 단계가 바로 이것입니다. 관찰한 내용을 바탕으로 다시 프로토타입을 고치는 순환이 이어집니다.',
    ],
    related: ['prototype', 'ux', 'ui'],
  },

  /* ---- PART 04. 노코드 프로토타이핑 ---- */
  {
    id: 'landing-page',
    emoji: '👉',
    term: '랜딩페이지',
    en: 'Landing Page',
    part: 'part04',
    kind: 'concept',
    short: '방문자가 처음 도착하는 한 장짜리 소개 페이지예요. 무엇을 해 주는 서비스인지 알리고, "신청하기" 같은 행동 하나로 이어지게 만드는 것이 목적입니다. 화면 하나에 목적을 하나만 담기 때문에, 아이디어를 빠르게 검증해 보는 용도로도 자주 쓰입니다. 🛬',
    body: [
      '보통 이런 순서로 구성합니다. 무엇인지 한 줄로 → 왜 좋은지 → 믿을 만한 근거(후기·숫자) → 눌러야 할 버튼 하나. 이것저것 다 담기보다 <strong>하나의 행동</strong>으로 모으는 것이 잘 만든 랜딩페이지예요.',
      '아이디어를 검증할 때도 씁니다. 제품을 다 만들기 전에 랜딩페이지만 먼저 띄워 두고, 사람들이 신청 버튼을 누르는지 보는 방법이 있어요.',
    ],
    related: ['prototype', 'v0'],
  },
  {
    id: 'lovable',
    emoji: '🛠️',
    term: 'Lovable',
    en: 'lovable.dev',
    part: 'part04',
    kind: 'tool',
    short: '채팅창에 "독서 기록을 남기는 앱을 만들어 줘"처럼 말하면, 진짜 동작하는 웹 앱을 통째로 만들어 주는 도구예요. 화면뿐 아니라 로그인과 데이터 저장까지 만들어 주고, 인터넷에 올리는 것까지 한 번에 됩니다. 서비스 하나를 처음부터 끝까지 대화만으로 완성해 보고 싶을 때 가장 먼저 떠올리게 되는 도구입니다. 🚀',
    body: [
      '보통 앱 하나를 만들려면 화면, 데이터를 담아 둘 곳, 로그인 기능을 따로따로 준비해야 합니다. Lovable은 이걸 대화만으로 한꺼번에 만들어 주기 때문에, 아이디어가 실제로 굴러가는 모습을 아주 빠르게 볼 수 있어요.',
      '만들어진 코드는 GitHub으로 내보낼 수 있습니다. 즉 여기서 시작해도 나중에 직접 손보거나 다른 도구로 옮겨 이어서 개발할 수 있습니다.',
    ],
    spectrum: { leftLabel: '화면 하나', rightLabel: '서비스 전체', value: 80 },
    related: ['v0', 'vibe-coding'],
  },
  {
    id: 'v0',
    emoji: '⚡',
    term: 'V0',
    en: 'v0.app · Vercel',
    part: 'part04',
    kind: 'tool',
    short: '원하는 화면을 말로 설명하거나 참고 이미지를 보여 주면, 그 화면을 코드로 만들어 주는 도구예요. Lovable이 앱 한 채를 짓는 쪽이라면, V0는 화면 한 장을 빠르게 뽑아 주는 쪽입니다. 이미 만들고 있는 프로젝트에 화면 하나만 빠르게 추가하고 싶을 때 특히 유용합니다. 🖼️',
    body: [
      '"가격표 세 개가 나란히 있는 요금제 화면"처럼 설명하면 몇 초 만에 화면이 나옵니다. 마음에 안 들면 다시 말해서 고칠 수 있어요.',
      '결과가 React + Tailwind CSS + shadcn/ui라는, 실무에서 널리 쓰는 형태의 코드로 나옵니다. 그래서 이미 만들고 있는 프로젝트에 그대로 가져다 붙이기 좋습니다.',
      '둘 중 하나만 골라야 하는 것은 아닙니다. 만들려는 것이 <strong>서비스 전체</strong>인지 <strong>화면 하나</strong>인지에 따라 나눠 씁니다.',
    ],
    spectrum: { leftLabel: '화면 하나', rightLabel: '서비스 전체', value: 20 },
    related: ['lovable', 'vibe-coding', 'vercel', 'react', 'tailwind-css', 'shadcn-ui'],
  },
  {
    id: 'google-ai-studio',
    emoji: '🔬',
    term: 'Google AI Studio',
    en: 'aistudio.google.com',
    part: 'part04',
    kind: 'tool',
    short: '구글의 Gemini AI 모델을 코드 한 줄 없이 브라우저에서 바로 써 볼 수 있는 콘솔이에요. 프롬프트를 입력하면 곧바로 결과가 나와서, 이 모델이 내가 원하는 걸 할 수 있는지 가볍게 찔러 볼 때 씁니다. 앱을 통째로 만들기 전에 성능부터 확인해 보는 첫 단계로 유용해요. 🔬',
    body: [
      '회원가입만 하면 설치 없이 브라우저에서 곧바로 프롬프트를 입력하고 결과를 받아 볼 수 있습니다. <strong>온도(temperature)</strong> 같은 세부 설정을 바꿔 가며 같은 질문에도 답이 어떻게 달라지는지 직접 눈으로 확인할 수 있어요.',
      '여기서 테스트한 프롬프트와 설정은 API 키와 코드 형태로 그대로 뽑아낼 수 있습니다. 실험은 가볍게 여기서 하고, 마음에 드는 결과가 나오면 실제 서비스 코드로 옮겨 붙이는 흐름으로 이어집니다.',
    ],
    note: '무료로 쓸 수 있는 건 Flash·Flash-Lite 계열 모델까지입니다. Gemini 2.5 Pro 같은 Pro 계열 모델은 2026년 4월부터 무료 티어에서 빠지고 결제 등록이 필요해졌어요. 🔒',
    related: ['v0', 'lovable', 'gemini'],
  },
  {
    id: 'firebase',
    emoji: '🧱',
    term: 'Firebase',
    en: 'firebase.google.com',
    part: 'part04',
    kind: 'tool',
    short: '구글이 만든, 데이터 저장(DB)·로그인·파일 저장 같은 뒷단 기능을 서버를 직접 만들지 않고도 갖다 쓸 수 있게 해 주는 서비스 모음이에요. 이런 서비스를 통틀어 BaaS(Backend as a Service)라고 부르는데, Firebase가 그 대표 주자입니다. 화면은 만들 줄 알아도 서버는 낯선 분들이 가장 먼저 붙여 보는 뒷단이에요. 🧱',
    body: [
      '회원가입·로그인, 데이터베이스, 파일 저장, 알림 발송 같은 기능을 각각 따로 서버를 세워서 만들 필요 없이 정해진 방식대로 <strong>불러다 쓰기만</strong> 하면 됩니다. 코드 몇 줄로 로그인 기능이 붙는 이유가 여기에 있어요.',
      '구글 계정으로 관리하기 때문에 구글의 다른 서비스(Google Auth 등)와도 잘 맞물립니다. 로그인·데이터베이스는 무료로 시작할 수 있는 범위가 넉넉한 편입니다.',
    ],
    note: '파일 저장(Cloud Storage) 기능은 2026년 2월부터 무료 Spark 플랜에서 아예 빠졌습니다. 사용량이 적어도 결제 카드가 연결된 Blaze 플랜으로 올려야 쓸 수 있어요. 💳',
    related: ['authentication', 'supabase', 'lovable', 'client-server'],
  },
  {
    id: 'supabase',
    emoji: '🐘',
    term: 'Supabase',
    en: 'supabase.com',
    part: 'part04',
    kind: 'tool',
    short: 'Firebase와 하는 일은 비슷하지만(로그인·DB·파일 저장을 서버 없이 갖다 쓰기), 오픈소스이고 안에서 표준 데이터베이스인 PostgreSQL을 그대로 쓴다는 점이 다른 서비스예요. "오픈소스 버전 Firebase"로 소개되는 경우가 많습니다. 이미 SQL을 알고 있다면 더 익숙하게 느껴질 수 있어요. 🐘',
    body: [
      'Firebase가 자체 방식(NoSQL)으로 데이터를 저장한다면, Supabase는 이미 널리 쓰이는 표준 데이터베이스인 <strong>PostgreSQL</strong>을 그대로 씁니다. 그래서 나중에 다른 곳으로 데이터를 옮기거나 SQL 지식을 그대로 활용하기가 더 쉽습니다.',
      '인증·스토리지·실시간 데이터 갱신 같은 기능도 Firebase와 비슷하게 갖추고 있어서, 두 서비스 중 어느 쪽을 고를지는 "데이터베이스를 표준 방식으로 쓰고 싶은가"가 갈림길이 되는 경우가 많습니다.',
    ],
    related: ['firebase', 'authentication', 'lovable', 'client-server'],
  },
  {
    id: 'authentication',
    emoji: '🔐',
    term: '인증',
    en: 'Authentication',
    part: 'part04',
    kind: 'concept',
    short: '"이 사용자가 정말 본인이 맞는지 확인하는 절차" 전체를 가리키는 개념이에요. 아이디·비밀번호를 맞춰 보는 것부터 문자 인증, 지문 인식까지 방식은 다양하지만 목적은 같습니다. 로그인 화면 뒤에서는 항상 이 절차가 돌아가고 있다고 보면 됩니다. 🔐',
    body: [
      'Firebase의 로그인 기능, Supabase의 인증 기능, Google Auth는 모두 이 개념을 실제로 구현해 주는 서로 다른 도구·방법입니다. 인증이 <strong>무엇을 해야 하는가</strong>를 가리키는 말이라면, 이 셋은 그것을 어떻게 해낼지에 대한 각자의 답인 셈이에요.',
      '직접 처음부터 만들려면 비밀번호 암호화, 이메일 인증, 세션 관리처럼 신경 쓸 부분이 많습니다. 그래서 대부분은 이미 검증된 서비스(Firebase, Supabase, Google Auth 등)를 가져다 쓰는 쪽을 택합니다.',
    ],
    related: ['firebase', 'supabase', 'google-auth'],
  },
  {
    id: 'client-server',
    emoji: '🛎️',
    term: '클라이언트-서버 구조',
    en: 'Client-Server Architecture',
    part: 'part04',
    kind: 'concept',
    short: '거의 모든 웹·앱 서비스가 돌아가는 기본 뼈대예요. 내가 쓰는 화면(클라이언트)이 "이거 해 줘"라고 요청을 보내면, 어딘가에 있는 컴퓨터(서버)가 처리해서 결과를 돌려줍니다. 식당에서 손님이 주문하면 주방이 요리해 내오는 것과 같은 구조예요. 🛎️',
    body: [
      '<strong>클라이언트</strong>는 브라우저, 스마트폰 앱처럼 사용자가 직접 만지는 쪽입니다. <strong>서버</strong>는 데이터를 저장하고 로그인을 확인하는 등 실제 처리를 맡는, 눈에 보이지 않는 컴퓨터예요. 클라이언트는 서버 없이는 데이터를 가져오거나 저장할 수 없고, 서버도 요청이 들어와야 비로소 일을 합니다.',
      '서버 하나가 동시에 여러 클라이언트를 상대합니다. 같은 서비스를 지금 이 순간 수백 명이 각자의 폰으로 쓰고 있어도, 그 뒤에는 보통 같은 서버(혹은 서버 무리)가 요청을 하나씩 처리하고 있는 것이죠. Firebase, Supabase 같은 도구는 이 서버 쪽을 직접 만들지 않고도 빌려 쓸 수 있게 해 줍니다.',
    ],
    note: '서버가 멈추면 클라이언트 화면은 멀쩡히 떠 있어도 데이터를 못 가져와 서비스 전체가 먹통이 됩니다. "화면은 뜨는데 아무것도 안 된다"면 대개 서버 쪽 문제입니다. ⚠️',
    flow: 'flowchart LR\n' +
          'A["클라이언트\\n(브라우저·앱)"] -- "요청" --> B["서버"]\n' +
          'B -- "응답" --> A',
    related: ['frontend-backend', 'api', 'firebase', 'supabase'],
  },
  {
    id: 'frontend-backend',
    emoji: '🍽️',
    term: '프론트엔드 / 백엔드',
    en: 'Frontend / Backend',
    part: 'part04',
    kind: 'concept',
    short: '클라이언트-서버 구조에서, 실제로 코드를 만드는 사람 입장에서 일감을 나누는 말이에요. 눈에 보이는 화면 쪽을 만드는 일이 프론트엔드, 데이터 저장·로그인 확인처럼 눈에 안 보이는 처리를 만드는 일이 백엔드입니다. 식당으로 치면 손님을 맞는 홀(프론트)과 요리하는 주방(백)이에요. 🍽️',
    body: [
      '<strong>프론트엔드</strong>는 클라이언트 쪽에서 돌아가는 화면을 만드는 일이라 HTML·CSS·JavaScript(React 등)를 주로 씁니다. <strong>백엔드</strong>는 서버 쪽에서 돌아가는 처리를 만드는 일로, JavaScript(Node.js)·Python 등 쓰는 언어와 실행 환경은 다양하지만 하는 역할은 "요청을 받아 데이터를 처리해서 돌려주기"로 같습니다.',
      '한 사람이 둘 다 만들면 <strong>풀스택(Full-stack)</strong>이라고 부릅니다. Next.js처럼 화면과 뒷단 처리를 한 프로젝트 안에서 같이 다룰 수 있게 해 주는 도구가 늘면서, 요즘은 이 경계가 예전만큼 뚜렷하지 않은 편입니다.',
    ],
    related: ['client-server', 'javascript', 'nextjs', 'firebase'],
  },

  /* ---- PART 05. 서비스 기획 ---- */
  {
    id: 'lean-startup',
    emoji: '🌱',
    term: '린 스타트업',
    en: 'Lean Startup',
    part: 'part05',
    kind: 'concept',
    short: '아이디어를 다 만들기 전에 최소한으로 빠르게 시도해 보고, 반응을 보고 고쳐 나가는 창업 방법론이에요. 몇 달을 들여 제품을 완성한 다음에야 "아무도 안 쓰네"라고 깨닫는 것이 가장 큰 낭비라는 생각에서 출발했습니다. "만들기 전에 검증한다"는 태도가 핵심이에요. 🌱',
    body: [
      '정식으로는 만들기(Build) → 측정하기(Measure) → 배우기(Learn)를 빠르게 반복하는 방식입니다. 최소한의 버전을 만들어서 실제 사람들에게 보여 주고, 반응을 숫자나 인터뷰로 확인한 다음, 그걸 바탕으로 다음 버전을 고칩니다.',
      '이 과정의 PART 5는 이름 자체가 "서비스 기획 & 린 스타트업"입니다. <strong>비즈니스 모델 캔버스</strong>로 아이디어를 정리하고 <strong>페르소나</strong>로 누구를 위한 것인지 구체화하는 것도 모두 이 태도의 연장선이에요.',
    ],
    note: '완벽한 제품을 만든 뒤 세상에 내놓겠다는 생각은 이 방법론과는 정반대입니다. 확신이 없을수록 더 빨리, 더 작게 시도해 보는 쪽이 린 스타트업의 방식이에요.',
    related: ['mvp', 'business-model-canvas', 'persona', 'prototype'],
  },
  {
    id: 'business-model-canvas',
    emoji: '🗺️',
    term: '비즈니스 모델 캔버스',
    en: 'Business Model Canvas · BMC',
    part: 'part05',
    kind: 'concept',
    short: '사업 아이디어를 고객, 가치제안, 수익구조 같은 몇 개의 칸으로 나눠서 한 장에 정리하는 표예요. 사업계획서처럼 수십 페이지를 쓰지 않아도, 이 표 하나만 채우면 아이디어의 뼈대가 한눈에 보입니다. 17회차 실습에서 팀별로 직접 채워 봅니다. 🗺️',
    body: [
      '보통 9개의 칸으로 구성됩니다. 고객이 누구인지, 그들에게 어떤 가치를 주는지, 어떻게 전달하는지, 무엇으로 돈을 버는지 같은 질문에 하나씩 답을 채워 넣는 방식이에요.',
      '한 번 채우고 끝내는 문서가 아닙니다. 고객 인터뷰나 <strong>페르소나</strong> 작업을 하면서 새롭게 알게 된 것이 있으면 다시 돌아와서 고쳐 씁니다. 표 전체가 계속 업데이트되는 살아있는 문서에 가깝습니다.',
    ],
    related: ['lean-startup', 'persona'],
  },
  {
    id: 'persona',
    emoji: '🧑',
    term: '페르소나',
    en: 'Persona',
    part: 'part05',
    kind: 'concept',
    short: '실제 있을 법한 대표 사용자 한 명을 구체적으로 상상해서 만드는 가상의 프로필이에요. "20대 여성"처럼 두루뭉술하게 두지 않고, 이름과 나이, 하루 일과, 겪고 있는 불편함까지 구체적으로 적습니다. "모두를 위한 서비스"는 방향을 정하기 어렵지만, 페르소나 한 명을 위한 서비스는 결정하기가 훨씬 쉬워져요. 🧑',
    body: [
      '예를 들어 "출퇴근길에 뉴스를 챙겨 보고 싶은데 시간이 없는 30대 직장인 지현씨"처럼 구체적으로 그려 두면, "지현씨라면 이 버튼을 누를까?"처럼 팀 안에서 판단 기준이 하나로 모입니다.',
      '상상만으로 채우면 안 됩니다. 16~17회차에서 다루는 <strong>고객 인터뷰</strong>를 통해 실제 사람들의 말과 행동을 근거로 삼아야, 페르소나가 팀의 희망사항이 아니라 진짜 사용자에 가까워집니다.',
    ],
    note: '페르소나를 한 번 만들고 나면 바꾸기 아깝다는 생각이 들 수 있지만, 인터뷰로 새로운 사실을 알게 되면 주저 없이 고쳐야 합니다.',
    related: ['business-model-canvas', 'lean-startup', 'ux'],
  },
  {
    id: 'google-auth',
    emoji: '🪪',
    term: 'Google Auth',
    en: 'Google OAuth',
    part: 'part05',
    kind: 'tool',
    short: '"Google로 계속하기" 버튼을 눌러 봤다면 이미 써 본 인증 방식이에요. 구글 계정으로 다른 서비스에 곧바로 로그인할 수 있게 해 주는 방식으로, 정식 명칭은 Google OAuth입니다. 사용자 입장에서는 새 비밀번호를 만들고 외울 필요가 없어서 가입 장벽이 확 낮아집니다. 🪪',
    body: [
      '사용자가 "구글로 로그인" 버튼을 누르면, 서비스는 비밀번호를 직접 보거나 저장하지 않고도 구글이 이 사람이 맞다고 확인해 준 결과만 넘겨받습니다. 그만큼 서비스 쪽에서 비밀번호를 안전하게 관리해야 하는 부담도 함께 줄어듭니다.',
      '랜딩페이지에 회원가입 절차를 통째로 만드는 대신 이 버튼 하나만 붙이면, 사용자는 몇 번 클릭만으로 로그인까지 끝낼 수 있습니다. 그만큼 첫 화면에서 이탈하는 사람을 줄이는 효과도 있어요.',
      'Firebase Authentication이나 Supabase Auth를 쓸 때도, 로그인 방식 목록 중 하나로 이 <strong>Google Auth</strong>를 골라서 함께 켤 수 있습니다. 서로 경쟁하는 관계가 아니라, 더 큰 인증 시스템 안에 포함되는 부품에 가깝습니다.',
    ],
    related: ['authentication', 'firebase', 'supabase'],
  },
  {
    id: 'pdf',
    emoji: '📕',
    term: 'PDF',
    en: 'Portable Document Format',
    part: 'part05',
    kind: 'concept',
    short: '어떤 기기·프로그램으로 열어도 글꼴과 줄 간격이 흐트러지지 않고 그대로 보이는 문서 형식이에요. 인쇄하듯 "고정된 모양"을 그대로 전달하고 싶을 때, 포트폴리오나 기획서를 제출할 때 가장 많이 씁니다. 📕',
    body: [
      '워드나 한글 파일은 여는 프로그램·글꼴 설치 여부에 따라 모양이 달라질 수 있지만, PDF는 만든 그대로의 모습을 보장합니다. 그래서 "최종본"을 주고받을 때 표준처럼 쓰입니다.',
      '이 과정의 포트폴리오, 서비스 기획서 산출물도 최종적으로는 PDF로 내보내서 제출하거나 공유하는 경우가 많습니다.',
    ],
    related: ['portfolio', 'business-model-canvas'],
  },

  /* ---- PART 06. 데이터 분석 & 머신러닝 ---- */
  {
    id: 'python',
    emoji: '🐍',
    logo: 'logos/python.svg',
    term: 'Python',
    en: '파이썬',
    part: 'part06',
    kind: 'lang',
    short: '문장이 영어와 비슷해서 읽기 쉬운 프로그래밍 언어예요. 데이터를 다루고 AI를 만드는 분야에서 가장 널리 쓰이고, 처음 배우는 언어로도 무난합니다. 다른 언어보다 짧은 코드로 같은 일을 해낼 수 있어서, 아이디어를 빠르게 실험해 보기에도 좋습니다. 📚',
    body: [
      '엑셀로 열기도 버거운 수만 줄짜리 데이터를 정리하고, 그래프로 그리고, 예측 모델을 만드는 일을 파이썬으로 합니다.',
      '필요한 기능은 대부분 다른 사람들이 미리 만들어 둔 꾸러미(라이브러리)를 가져다 씁니다. 그래서 밑바닥부터 만들 일은 거의 없어요.',
      '문법을 다 외운 다음에 시작할 필요는 없습니다. AI에게 물어 가며 쓰다 보면 필요한 만큼 자연스럽게 익혀집니다.',
    ],
    flow: 'flowchart LR\n' +
          'A["Python"] --> B["NumPy"]\n' +
          'B --> C["pandas"]\n' +
          'C --> D["Matplotlib"]\n' +
          'C --> E["Plotly"]',
    related: ['data-analysis', 'machine-learning', 'pandas'],
  },
  {
    id: 'numpy',
    emoji: '🔢',
    term: 'NumPy',
    en: 'numpy.org',
    part: 'part06',
    kind: 'tool',
    short: '파이썬에서 숫자로 가득한 커다란 표(배열)를 아주 빠르게 계산할 수 있게 해 주는 기초 도구예요. 뒤에서 다룰 pandas, matplotlib 같은 도구들이 이 위에 서 있습니다. 화면에 직접 드러나지는 않지만, 데이터를 다루는 거의 모든 파이썬 도구의 밑바탕을 이루고 있습니다. ⚙️',
    body: [
      '파이썬 반복문으로 숫자를 하나씩 계산하면 데이터가 많아질수록 느려집니다. NumPy는 이런 계산을 통째로 빠르게 처리하도록 특별히 만들어진 도구예요.',
      'NumPy 문법을 직접 외워서 쓸 일은 생각보다 적습니다. "다른 데이터 도구들이 속으로 이걸 쓰고 있구나" 정도만 알아도 수업을 따라가는 데 충분합니다.',
    ],
    related: ['python', 'pandas'],
  },
  {
    id: 'pandas',
    emoji: '🐼',
    term: 'pandas',
    en: 'pandas.pydata.org',
    part: 'part06',
    kind: 'tool',
    short: '엑셀 표처럼 생긴 데이터를 파이썬에서 불러오고, 정리하고, 계산할 수 있게 해 주는 도구예요. 데이터 분석을 시작할 때 가장 먼저 배우는 도구입니다. 엑셀로는 며칠 걸릴 정리 작업도 코드 몇 줄이면 끝나서, 반복 작업을 크게 줄여 줍니다. 🗂️',
    body: [
      'CSV나 엑셀 파일을 몇 줄의 코드로 불러온 뒤, 조건에 맞는 행만 골라내거나 평균·합계를 구하는 일을 아주 빠르게 할 수 있습니다.',
      'NumPy 위에 만들어진 도구라서, 수만 줄짜리 데이터를 다뤄도 크게 느려지지 않습니다.',
    ],
    related: ['numpy', 'data-analysis', 'python', 'csv'],
  },
  {
    id: 'csv',
    emoji: '📋',
    term: 'CSV',
    en: 'Comma-Separated Values',
    part: 'part06',
    kind: 'concept',
    short: '쉼표(,)로 값을 구분해서 표 형태의 데이터를 담는 가장 단순한 파일 형식이에요. 엑셀로 열면 표로 바로 보이고, 파이썬의 pandas 같은 도구로도 몇 줄 만에 불러올 수 있어서 데이터 분석의 가장 기본적인 입력 형식입니다. 📊',
    body: [
      '쉼표로 열을 나누고 줄바꿈으로 행을 나누는 것이 전부라서 구조가 아주 단순합니다. 그만큼 어떤 프로그래밍 언어·도구에서도 빠짐없이 지원합니다.',
      '이 과정 데이터 분석 실습에서 가장 먼저 마주치는 파일 형식입니다. <strong>pandas</strong>로 CSV를 불러온 뒤 조건에 맞는 행을 고르거나 평균을 구하는 식으로 실습이 이어집니다.',
    ],
    related: ['pandas', 'data-analysis', 'xlsx', 'json'],
  },
  {
    id: 'xlsx',
    emoji: '📈',
    term: 'XLSX (엑셀)',
    en: 'Microsoft Excel',
    part: 'part06',
    kind: 'concept',
    short: '표 데이터를 다루는 마이크로소프트 엑셀의 기본 파일 형식이에요. CSV와 달리 시트를 여러 개 담을 수 있고, 셀마다 색깔·수식·차트 같은 꾸밈과 계산 기능을 함께 저장합니다. 📈',
    body: [
      'CSV가 "숫자와 글자만 있는 표"라면, XLSX는 그 표에 수식·서식·여러 시트·차트까지 얹은 형식입니다. 그만큼 파일이 무겁고 구조도 복잡해서, 프로그램으로 다루려면 CSV보다 손이 더 갑니다.',
      '데이터 분석 실습에서는 원본이 엑셀로 오는 경우가 많아, 이를 CSV로 저장하거나 pandas로 직접 읽어 들여 분석에 쓰는 흐름이 흔합니다.',
    ],
    related: ['csv', 'data-analysis'],
  },
  {
    id: 'ipynb',
    emoji: '📓',
    term: 'Jupyter Notebook (.ipynb)',
    en: 'Jupyter',
    part: 'part06',
    kind: 'concept',
    short: '코드와 그 실행 결과(표, 그래프), 설명 글을 한 파일 안에 순서대로 섞어서 담을 수 있는 파일 형식이에요. 코드를 조금씩 나눠 실행해 보면서 데이터를 탐색하는 데이터 분석·머신러닝 작업에 특히 잘 맞습니다. 📓',
    body: [
      '.py 파일은 코드만 위에서 아래로 쭉 실행하지만, .ipynb는 "셀" 단위로 코드를 나눠서 하나씩 따로 실행하고 결과를 바로 아래에서 확인할 수 있습니다. 그래프나 표를 코드 바로 옆에 남길 수 있어 분석 과정을 기록하기에도 좋습니다.',
      '이 과정의 데이터 분석·머신러닝 실습 대부분이 이 형식으로 진행됩니다. Google Colab이나 VS Code에서 열어 바로 실행해 볼 수 있습니다.',
    ],
    related: ['data-analysis', 'machine-learning', 'pandas', 'python'],
  },
  {
    id: 'matplotlib',
    emoji: '📐',
    term: 'Matplotlib',
    en: 'matplotlib.org',
    part: 'part06',
    kind: 'tool',
    short: '파이썬으로 숫자 데이터를 선 그래프, 막대 그래프 같은 그림으로 그려 주는 가장 기본적인 도구예요. 분석한 결과를 눈으로 확인할 때 씁니다. 오래전부터 쓰여 온 만큼 자료도 많고, 웬만한 그래프는 다 그릴 수 있을 만큼 기능이 탄탄합니다. 📊',
    body: [
      '색깔, 글씨 크기, 축 눈금까지 세세하게 직접 지정할 수 있어서 자유도가 높은 대신, 원하는 모양을 만들려면 코드가 다소 길어질 수 있습니다.',
      '마우스로 확대하거나 값을 찍어 보는 것 같은 상호작용은 되지 않는, 한 장의 정지된 그림에 가깝습니다. 그런 상호작용이 필요하면 <strong>Plotly</strong>를 함께 씁니다.',
    ],
    spectrum: { leftLabel: '정적', rightLabel: '인터랙티브', value: 15 },
    related: ['pandas', 'plotly'],
  },
  {
    id: 'plotly',
    emoji: '🖱️',
    term: 'Plotly',
    en: 'plotly.com',
    part: 'part06',
    kind: 'tool',
    short: '마우스로 확대하거나 그래프 위에 갖다 대면 값이 뜨는 것처럼, 직접 눌러 보고 움직여 볼 수 있는 그래프를 만들어 주는 도구예요. 발표 자료나 대시보드에 넣기 좋습니다. 보는 사람이 스스로 궁금한 부분을 파고들 수 있어서, 결과를 일방적으로 보여주기보다 함께 탐색하고 싶을 때 유리합니다. 🎛️',
    body: [
      'Matplotlib이 정지된 사진 같은 그래프라면, Plotly는 화면 안에서 움직이는 그래프에 가깝습니다. 같은 그래프라도 상대방이 직접 들여다볼 수 있게 하고 싶을 때 씁니다.',
      '파이썬뿐 아니라 웹페이지(자바스크립트)에서도 똑같은 방식으로 쓸 수 있어서, 만든 그래프를 그대로 웹사이트에 옮겨 놓기도 쉽습니다.',
    ],
    related: ['matplotlib', 'data-analysis'],
  },
  {
    id: 'data-analysis',
    emoji: '📊',
    term: '데이터 분석',
    en: 'Data Analysis',
    part: 'part06',
    kind: 'concept',
    short: '쌓여 있는 숫자와 기록을 들여다보면서 "지금 무슨 일이 벌어지고 있는지" 알아내는 일이에요. 어느 화면에서 사람들이 떠나는지, 어떤 기능이 실제로 쓰이는지를 감이 아니라 근거로 말할 수 있게 해 줍니다. 결과가 항상 거창할 필요는 없고, 작은 숫자 하나가 다음 결정을 바꾸는 경우도 많습니다. 🔍',
    body: [
      '예를 들어 가입 화면에서 사용자의 80%가 그냥 나가 버린다는 사실을 발견했다고 해 볼게요. 그러면 "물어보는 항목이 너무 많은 것 아닐까?" 같은 다음 질문으로 이어집니다. 기획과 디자인을 고치는 근거가 여기서 나옵니다.',
      '엑셀로 시작해서 파이썬 같은 도구까지 쓰게 되지만, 도구보다 중요한 것은 <strong>무엇을 알고 싶은지 정하는 일</strong>입니다. 질문이 흐릿하면 아무리 좋은 도구를 써도 답이 나오지 않아요.',
      '머신러닝과 자주 붙어 다니지만 목적이 다릅니다. 데이터 분석은 주로 "무슨 일이 있었나"를 이해하는 쪽, 머신러닝은 "다음엔 어떻게 될까"를 예측하는 쪽에 가깝습니다.',
    ],
    related: ['machine-learning', 'csv', 'ipynb', 'pandas'],
  },
  {
    id: 'machine-learning',
    emoji: '🤖',
    term: '머신러닝',
    en: 'Machine Learning · 기계학습',
    part: 'part06',
    kind: 'concept',
    short: '규칙을 사람이 일일이 정해 주는 대신, 컴퓨터가 많은 데이터를 보면서 스스로 패턴을 찾아내게 하는 방법이에요. 스팸 메일을 걸러내거나 사진 속 얼굴을 알아보는 기능이 이렇게 만들어집니다. 사람이 규칙을 일일이 못 정할 만큼 복잡한 문제일수록 이 방식이 빛을 발합니다. 📈',
    body: [
      '고양이 사진을 수천 장 보여 주면, 컴퓨터가 "고양이는 대체로 이렇게 생겼다"를 스스로 익힙니다. 사람이 "귀가 뾰족하고 수염이 있고..."를 코드로 적어 줄 필요가 없다는 것이 핵심이에요.',
      '그래서 결과의 품질은 <strong>데이터의 양과 질</strong>에 크게 좌우됩니다. 한쪽으로 치우친 데이터를 학습하면 결과도 치우칩니다.',
      '요즘 이야기되는 AI 대부분이 머신러닝 위에 서 있습니다. ChatGPT 같은 LLM도 머신러닝의 한 갈래예요.',
    ],
    flow: 'flowchart LR\n' +
          'A["머신러닝"] -- "그 중 한 갈래" --> B["LLM"]\n' +
          'B -- "도구 사용 능력 추가" --> C["AI Agent"]',
    related: ['data-analysis', 'llm', 'tensorflow', 'pytorch'],
  },
  {
    id: 'tensorflow',
    emoji: '🌊',
    logo: 'logos/tensorflow.svg',
    term: 'TensorFlow',
    en: 'tensorflow.org · Google',
    part: 'part06',
    kind: 'tool',
    short: '구글이 만든, 머신러닝 모델을 직접 설계하고 학습시킬 수 있게 해 주는 대표적인 도구예요. 사진 인식, 음성 인식 같은 복잡한 모델도 이걸로 만듭니다. 대규모 서비스에 모델을 실제로 올려 운영하는 단계까지 고려해서 만들어진 도구라, 연구용으로 짠 모델을 서비스로 옮길 때 특히 강점을 보입니다. 🏗️',
    body: [
      '"규칙을 코드로 직접 적는 것"이 아니라, 데이터를 많이 보여 주면서 <strong>모델 스스로 규칙을 찾게 만드는</strong> 머신러닝 학습 과정을 실제로 돌려 주는 도구입니다.',
      '처음부터 모델을 새로 설계하기보다, 이미 만들어진 모델을 가져와서 내 데이터에 맞게 살짝 손보는 식으로도 충분히 실습할 수 있습니다.',
    ],
    note: 'TensorFlow와 PyTorch는 하는 일이 거의 같습니다. 최근에는 연구 쪽에서 PyTorch, 실제 서비스에 모델을 올리는 쪽에서 TensorFlow가 조금 더 흔히 쓰이는 편이지만, 절대적인 기준은 아닙니다.',
    spectrum: { leftLabel: '연구', rightLabel: '프로덕션 배포', value: 70 },
    related: ['machine-learning', 'pytorch', 'python'],
  },
  {
    id: 'pytorch',
    emoji: '🔥',
    logo: 'logos/pytorch.svg',
    term: 'PyTorch',
    en: 'pytorch.org · Meta',
    part: 'part06',
    kind: 'tool',
    short: '메타(옛 페이스북)가 만든, TensorFlow와 목적이 같은 머신러닝 도구예요. 문법이 파이썬 코드처럼 자연스럽게 읽혀서 최근 연구 쪽에서 특히 많이 쓰입니다. 새로운 아이디어를 빠르게 시도해 보고 싶어 하는 연구자들 사이에서 사실상 표준으로 자리잡았습니다. 🐍',
    body: [
      'ChatGPT 같은 최신 LLM 대부분이 이 도구로 만들어졌을 만큼, 요즘 AI 연구에서 사실상 표준처럼 쓰이는 도구입니다.',
      'TensorFlow보다 어느 쪽이 낫다기보다, 하는 일은 거의 같고 문법과 생태계가 다른 정도로 이해하면 됩니다.',
    ],
    spectrum: { leftLabel: '연구', rightLabel: '프로덕션 배포', value: 25 },
    related: ['tensorflow', 'machine-learning'],
  },
  {
    id: 'playwright',
    emoji: '🎭',
    term: 'Playwright',
    en: 'playwright.dev',
    part: 'part06',
    kind: 'tool',
    short: '진짜 브라우저를 코드로 직접 켜고 조작해서 웹페이지 내용을 긁어오는 도구예요. 버튼을 눌러야 열리는 메뉴나 스크롤을 내려야 나타나는 목록처럼 동적인 화면도, 실제로 클릭하고 스크롤하면서 데이터를 가져올 수 있습니다. 정적인 페이지만 읽는 방법으로는 손이 닿지 않는 곳까지 긁어낼 수 있어요. 🎭',
    body: [
      '단순히 HTML 문서를 다운로드해서 읽는 방식으로는, 자바스크립트가 나중에 채워 넣는 내용은 보이지 않습니다. Playwright는 <strong>실제 브라우저를 띄워서</strong> 페이지가 완전히 로딩되고 동작한 뒤의 화면을 그대로 가져오기 때문에, 이런 동적인 페이지도 문제없이 다룰 수 있습니다.',
      '"이 버튼을 클릭 → 이 입력창에 검색어 입력 → 결과 목록에서 텍스트 추출"처럼, 사람이 브라우저에서 하는 행동을 코드로 그대로 옮겨 적는 식으로 씁니다. 원래는 웹사이트가 잘 동작하는지 자동으로 테스트하는 용도로 만들어진 도구인데, 같은 능력이 크롤링에도 그대로 쓰입니다.',
    ],
    note: '브라우저를 통째로 띄우는 방식이라 속도는 느리고 컴퓨터 자원도 더 씁니다. 페이지가 단순한 정적 페이지라면 굳이 이걸 쓰지 않아도 되는 경우가 많아요. 사이트마다 크롤링을 허용하는 범위(robots.txt, 이용약관)가 다르니 확인하고 씁니다. 🐢',
    related: ['web-crawling', 'python', 'rss', 'open-api'],
  },
  {
    id: 'web-crawling',
    emoji: '🕷️',
    term: '웹 크롤링',
    en: 'Web Crawling',
    part: 'part06',
    kind: 'concept',
    short: '웹사이트 여러 페이지를 자동으로 돌아다니며 필요한 데이터를 긁어모으는 방법 전체를 가리키는 말이에요. 사람이 일일이 페이지를 열어 보고 복사·붙여넣기 하는 대신, 코드가 대신 돌아다니며 모아 줍니다. Playwright는 이 일을 해내는 여러 도구 중 하나입니다. 🕷️',
    body: [
      '단순한 페이지는 코드가 그냥 문서를 요청해서 읽는 것만으로 충분하지만, 로그인이 필요하거나 버튼을 눌러야 내용이 나오는 페이지는 <strong>Playwright</strong> 같은, 브라우저를 직접 조작하는 도구가 필요합니다. 무엇을 크롤링하느냐에 따라 알맞은 방법이 달라지는 셈이에요.',
      'RSS나 공공데이터 Open API처럼 사이트가 데이터를 <strong>미리 정리해서 내주는 통로</strong>가 있다면, 굳이 크롤링하지 않고 그쪽을 쓰는 것이 훨씬 간단하고 안정적입니다. 크롤링은 그런 통로가 없을 때 마지막으로 꺼내는 방법에 가깝습니다.',
    ],
    note: '사이트마다 크롤링을 허용하는 범위와 방법이 다릅니다. robots.txt나 이용약관을 확인하고, 짧은 시간에 너무 많은 요청을 보내 서버에 부담을 주지 않도록 조심합니다. ⚠️',
    related: ['playwright', 'rss', 'open-api'],
  },
  {
    id: 'rss',
    emoji: '📡',
    term: 'RSS',
    en: 'Really Simple Syndication',
    part: 'part06',
    kind: 'concept',
    short: '뉴스·블로그 사이트에 새 글이 올라올 때마다, 구독자에게 정해진 형식으로 알려 주는 오래된 웹 표준이에요. 사이트를 하나하나 들어가서 확인하지 않아도, RSS 주소 하나만 구독해 두면 새 글 목록을 한곳에서 받아 볼 수 있습니다. 요즘은 잘 안 쓰다 보니 오히려 낯설게 느껴질 수 있어요. 📡',
    body: [
      '지금처럼 SNS나 뉴스 앱이 자리잡기 전, 여러 사이트의 새 글을 한곳에서 모아 보기 위해 널리 쓰이던 방식입니다. 사이트 운영자가 <code>/rss</code>나 <code>/feed</code> 같은 주소에 새 글 목록을 표준화된 형식(XML)으로 계속 갱신해 두면, RSS 리더라는 프로그램이 그 주소들을 주기적으로 확인해서 새 글을 모아 보여 줍니다.',
      '요즘은 SNS에 밀려 잘 보이지 않지만, 여전히 많은 뉴스·블로그 사이트가 RSS 주소를 열어 두고 있습니다. 코드로 이 주소를 읽으면 <strong>제목·링크·날짜가 이미 깔끔하게 정리된 데이터</strong>를 바로 받을 수 있어서, 크롤링보다 훨씬 손쉬운 데이터 수집 방법이 됩니다.',
    ],
    related: ['web-crawling', 'open-api'],
  },
  {
    id: 'open-api',
    emoji: '🏛️',
    term: '공공데이터 Open API',
    en: 'Open API',
    part: 'part06',
    kind: 'concept',
    short: '정부나 공공기관이 인구, 날씨, 대중교통처럼 갖고 있는 데이터를 누구나 가져다 쓸 수 있게 표준화된 형식으로 공개해 둔 창구예요. 회원가입하고 API 키를 받으면, 정해진 방식으로 요청을 보내 필요한 데이터를 바로 받을 수 있습니다. 크롤링하지 않아도 되는, 가장 깔끔한 데이터 수집 방법입니다. 🏛️',
    body: [
      '공공데이터포털(data.go.kr) 같은 곳에 가면, 기관마다 흩어져 있던 데이터를 <strong>표준화된 API 형태</strong>로 정리해 둔 것을 볼 수 있습니다. "서울시 버스 도착 정보"나 "지역별 인구 통계" 같은 데이터를 코드 몇 줄로 바로 받아 올 수 있어요.',
      '앞서 배운 <strong>API</strong>라는 개념의 한 종류입니다. 일반 API는 회사가 자기 서비스를 위해 열어 둔 창구인 데 비해, 공공데이터 Open API는 세금으로 만들어진 데이터를 시민 누구나 쓸 수 있게 열어 둔 창구라는 점이 다릅니다.',
    ],
    note: '기관마다 데이터 형식과 문서 수준이 제각각입니다. 신청 후 승인까지 시간이 걸리는 경우도 있으니, 실습보다 며칠 여유를 두고 키를 미리 신청해 두면 좋습니다. 🗝️',
    related: ['api', 'rss', 'web-crawling'],
  },
  {
    id: 'kaggle',
    emoji: '🏆',
    term: '캐글',
    en: 'Kaggle',
    part: 'part06',
    kind: 'tool',
    short: '전 세계 데이터 과학자들이 데이터셋을 올려 공유하고, 정해진 문제를 놓고 예측 모델 성능을 겨루는 온라인 커뮤니티예요. 회원가입만 하면 다양한 주제의 정리된 데이터셋을 무료로 내려받을 수 있어서, 연습용 데이터를 찾을 때 가장 먼저 들르게 되는 곳입니다. 대회에 직접 참가하지 않고 데이터만 구경해도 충분히 쓸모 있습니다. 🏆',
    body: [
      '"타이타닉 생존자 예측", "집값 예측"처럼 머신러닝을 처음 배울 때 연습하기 좋은 데이터셋이 이미 잘 정리된 채로 잔뜩 올라와 있습니다. 직접 크롤링하거나 공공데이터 API를 뒤지지 않아도, 검색 한 번으로 <strong>바로 분석을 시작할 수 있는 데이터</strong>를 구할 수 있어요.',
      '다른 사람들이 같은 데이터로 어떻게 분석했는지 공개해 둔 노트북(코드)도 함께 볼 수 있습니다. 막막할 때 참고할 예시가 많다는 것도 이 플랫폼의 큰 장점입니다.',
    ],
    related: ['data-analysis', 'machine-learning', 'eda'],
  },
  {
    id: 'deep-learning',
    emoji: '🕸️',
    term: '딥러닝',
    en: 'Deep Learning',
    part: 'part06',
    kind: 'concept',
    short: '사람 뇌의 뉴런이 연결된 구조를 흉내 낸 인공신경망을, 여러 겹으로 깊게 쌓아서 학습시키는 머신러닝의 한 갈래예요. 층을 깊게 쌓을수록 더 복잡하고 미묘한 패턴까지 스스로 잡아낼 수 있게 됩니다. 요즘 화제가 되는 LLM이나 이미지 인식 AI 대부분이 이 방식으로 만들어집니다. 🕸️',
    body: [
      '머신러닝이 "데이터를 보고 스스로 패턴을 찾는 방법" 전체를 가리킨다면, 딥러닝은 그 중에서도 <strong>인공신경망을 여러 층 쌓은 방식</strong>을 쓰는 갈래입니다. 층이 깊어질수록 사람이 일일이 설계하지 않아도 훨씬 복잡한 특징을 스스로 잡아낼 수 있게 됩니다.',
      '사진 속 물체를 알아보고, 사람 말을 이해해서 글로 답하는 것처럼 최근 화제가 되는 화려한 AI 기능 대부분이 이 방식 위에 서 있습니다. ChatGPT나 Claude 같은 LLM도 딥러닝으로 학습된 인공신경망입니다.',
    ],
    flow: 'flowchart LR\n' +
          'A["머신러닝"] -- "그 중 한 갈래" --> B["딥러닝"]\n' +
          'B -- "특히 언어에 특화" --> C["LLM"]',
    related: ['machine-learning', 'llm', 'tensorflow', 'pytorch'],
  },
  {
    id: 'eda',
    emoji: '🔎',
    term: 'EDA',
    en: 'Exploratory Data Analysis · 탐색적 데이터 분석',
    part: 'part06',
    kind: 'concept',
    short: '본격적으로 분석하거나 모델을 만들기 전에, 그래프와 기본 통계로 데이터를 먼저 쭉 훑어보는 단계예요. 데이터에 어떤 특징이 있는지, 이상한 값이나 빠진 값은 없는지를 미리 파악해 둡니다. 준비 운동 없이 바로 분석에 들어가면 나중에 엉뚱한 결과를 붙잡고 헤매기 쉽습니다. 🔎',
    body: [
      '평균·최댓값 같은 기본 통계를 확인하고, 히스토그램이나 산점도 같은 그래프로 데이터를 그려 보면서 <strong>"이 데이터가 대체로 어떻게 생겼는지"</strong>를 감으로 익히는 과정입니다. pandas로 표를 들여다보고 Matplotlib·Plotly로 그려 보는 작업이 대부분 여기 해당합니다.',
      '이 단계에서 이상치(다른 값들과 동떨어진 값)나 빠진 값을 미리 발견해 두면, 나중에 모델을 만들 때 엉뚱한 값 때문에 결과가 왜곡되는 것을 미리 막을 수 있습니다. 캐글 같은 곳에서 데이터를 받아도, 분석에 앞서 이 과정을 먼저 거치는 것이 순서예요.',
    ],
    related: ['data-analysis', 'pandas', 'kaggle'],
  },

  /* ---- PART 07. LLM · RAG · Agent ---- */
  {
    id: 'llm',
    emoji: '🧠',
    term: 'LLM',
    en: 'Large Language Model · 대규모 언어 모델',
    part: 'part07',
    kind: 'concept',
    short: 'ChatGPT나 Claude처럼 사람의 말을 알아듣고 글로 답해 주는 AI를 말해요. 엄청난 양의 글을 학습해서 "이 다음에 올 말"을 아주 잘 맞히는 방식으로 동작합니다. 질문 하나로 요약·번역·코드 작성까지 다 해낼 만큼 쓰임새가 넓어서, 이 과정에서 쓰는 도구 대부분이 이 위에서 돌아갑니다. 💡',
    body: [
      '사람처럼 뜻을 이해한다기보다, 지금까지의 문맥을 보고 가장 그럴듯한 다음 말을 이어 붙이는 쪽에 가깝습니다. 그런데 그걸 아주 잘하다 보니 요약, 번역, 코드 작성까지 해내는 것이죠.',
      '이 과정에서 쓰는 바이브코딩 도구도, 노코드 도구도 안에서는 결국 LLM이 돌아가고 있습니다. 그래서 LLM의 성질을 알면 "왜 이 도구가 이렇게 반응하지?"를 이해하기 쉬워집니다.',
    ],
    note: '모르는 것도 아는 것처럼 그럴듯하게 지어내는 일이 있습니다(환각, hallucination). 숫자·날짜·인용처럼 사실이 중요한 내용은 꼭 사람이 확인해야 합니다. ⚠️',
    related: ['ai-agent', 'machine-learning', 'vibe-coding', 'chatgpt', 'claude', 'gemini', 'grok'],
  },
  {
    id: 'ai-agent',
    emoji: '🦾',
    term: 'AI Agent',
    en: 'AI 에이전트',
    part: 'part07',
    kind: 'concept',
    short: '물어보면 답만 해 주는 것을 넘어, 목표를 주면 스스로 순서를 정하고 도구까지 써 가며 일을 끝내는 AI예요. 검색하고, 파일을 고치고, 결과가 맞는지 확인하는 것까지 알아서 합니다. 사람이 매 단계마다 지시하지 않아도 되기 때문에, 한 번의 요청으로 여러 단계짜리 작업을 맡길 수 있습니다. 🔁',
    body: [
      '"이번 주 매출을 정리해서 메일 초안까지 써 줘"라고 하면, 자료를 찾고 → 표로 만들고 → 초안을 쓰는 여러 단계를 알아서 밟습니다. 한 번의 질문과 한 번의 답으로 끝나지 않는다는 점이 다릅니다.',
      'LLM이 <strong>두뇌</strong>라면 에이전트는 <strong>손발까지 달린 상태</strong>라고 생각하면 쉽습니다. 수업에서 쓰는 클로드 코드 같은 도구가 바로 이 형태예요.',
    ],
    note: '스스로 실행하기 때문에, 무엇까지 하도록 허락할지 정하는 일이 중요해집니다. 파일을 지우거나 외부로 무언가를 보내는 동작은 특히 조심해서 다룹니다.',
    related: ['llm', 'mcp', 'vibe-coding', 'sub-agent'],
  },
  {
    id: 'sub-agent',
    emoji: '🧵',
    term: '서브에이전트',
    en: 'Subagent',
    part: 'part07',
    kind: 'concept',
    short: '메인 AI가 혼자 다 하지 않고, 특정 작업만 맡을 작은 AI를 따로 불러서 시키는 방식이에요. 코드 검색은 검색 담당에게, 파일 수정은 수정 담당에게 나눠 맡기는 식입니다. 여러 작업을 동시에 진행하거나, 각자 필요한 정보만 보게 해서 더 정확하게 일을 시킬 수 있습니다. 🧵',
    body: [
      '회사에서 팀장이 모든 일을 혼자 처리하지 않고 담당자에게 나눠 맡기는 것과 비슷합니다. 메인 에이전트는 "무엇을 시킬지"만 정하고, 실제 작업은 서브에이전트가 독립적으로 진행한 뒤 결과만 보고합니다.',
      '서브에이전트는 메인 대화의 전체 맥락을 다 보지 않고 필요한 지시만 받기 때문에, 크고 복잡한 작업을 쪼개서 시켜도 각자는 자기 몫에만 집중할 수 있습니다. 여러 개를 동시에(병렬로) 띄우면 순서대로 하나씩 시키는 것보다 훨씬 빨리 끝낼 수도 있습니다.',
    ],
    note: '서브에이전트가 무엇을 했는지는 최종 보고로만 확인되고, 중간 과정은 메인 대화에 남지 않습니다. 결과가 이상하면 어느 서브에이전트가 무엇을 했는지 다시 확인하는 습관이 필요합니다.',
    related: ['ai-agent', 'claude-code', 'mcp'],
  },
  {
    id: 'api',
    emoji: '🔌',
    term: 'API',
    en: 'Application Programming Interface',
    part: 'part07',
    kind: 'concept',
    short: '프로그램끼리 정해진 방식으로 서로 말을 주고받는 창구예요. 식당의 주문서처럼 "이렇게 요청하면 이런 걸 돌려준다"는 약속이라고 생각하면 쉽습니다. 이 약속만 지키면 되기 때문에, 상대 프로그램이 내부적으로 어떻게 동작하는지는 몰라도 기능을 가져다 쓸 수 있습니다. 🤝',
    body: [
      '예를 들어 날씨 API에 도시 이름을 보내면 기온을 돌려줍니다. 기상청 시스템이 안에서 어떻게 돌아가는지 하나도 몰라도, 약속된 방식으로 요청만 하면 되는 것이죠.',
      '내가 만든 앱에 AI 기능을 넣는 것도 결국 LLM의 API를 부르는 일입니다. 지도, 결제, 로그인처럼 직접 만들기 어려운 기능을 남이 만들어 둔 것으로 채울 때도 API를 씁니다.',
    ],
    note: 'API 키(key)는 비밀번호와 같습니다. 코드에 그대로 적어 GitHub에 올리면 남이 내 이름으로 쓰고 요금까지 나올 수 있어요. 이 부분은 수업에서 따로 다룹니다. 🔐',
    flow: 'flowchart LR\n' +
          'A["내 앱"] -- "요청" --> B["API"]\n' +
          'B -- "응답" --> A',
    related: ['mcp', 'llm', 'client-server'],
  },
  {
    id: 'mcp',
    emoji: '🔗',
    term: 'MCP',
    en: 'Model Context Protocol',
    part: 'part07',
    kind: 'concept',
    short: 'AI가 바깥 도구나 자료에 연결되는 방식을 하나로 통일해 둔 약속이에요. AI에 무언가를 꽂아 쓰는 USB 단자 같은 것이라고 생각하면 쉽습니다. 도구마다 연결 방법을 따로 만들 필요가 없어서, 한 번 만들어 둔 연결을 여러 AI에서 그대로 재사용할 수 있습니다. 🔌',
    body: [
      '예전에는 AI마다, 도구마다 연결 방법을 따로 만들어야 했습니다. MCP라는 공통 규격을 지키면 한 번 만들어 둔 연결을 여러 AI에서 그대로 쓸 수 있어요.',
      '예를 들어 노션 MCP를 붙이면 AI가 내 노션 문서를 읽고 쓸 수 있게 됩니다. 에이전트가 실제로 일을 하려면 이런 연결이 필요하죠.',
      '2024년 말 앤트로픽(Anthropic)이 공개한 뒤 여러 도구가 따라 쓰기 시작했습니다.',
    ],
    flow: 'flowchart LR\n' +
          'A["AI"] --> B["MCP"]\n' +
          'B --> C["노션"]\n' +
          'B --> D["파일"]\n' +
          'B --> E["DB · 외부 도구"]',
    related: ['ai-agent', 'api'],
  },
  {
    id: 'rag',
    emoji: '📖',
    term: 'RAG',
    en: 'Retrieval-Augmented Generation',
    part: 'part07',
    kind: 'concept',
    short: 'LLM이 원래 모르는 최신 정보나 내 문서 내용을 검색해서 답변에 반영하게 만드는 방식이에요. "책을 통째로 외운 기억만으로 답하기" 대신 "질문에 맞는 자료를 먼저 찾아본 다음 답하기"에 가깝다고 생각하면 쉽습니다. 시험 볼 때 오픈북을 허용해 주는 것과 비슷해요. 📖',
    body: [
      'LLM은 학습이 끝난 시점까지의 정보만 알고 있어서, 내 회사 문서나 어제 올라온 뉴스는 알 수 없습니다. RAG는 질문이 들어오면 관련된 자료를 먼저 <strong>검색(Retrieval)</strong>해서 찾아낸 뒤, 그 내용을 함께 넣어 LLM이 답을 <strong>생성(Generation)</strong>하게 만드는 방식이에요. 이름 그대로 "검색으로 보강한 생성"입니다.',
      '가장 큰 효과는 LLM의 <strong>환각(hallucination)</strong>을 줄이는 것입니다. 모르는 것도 그럴듯하게 지어내던 LLM이, 실제 문서를 옆에 두고 답하게 되면 훨씬 근거 있는 답을 내놓습니다.',
      '이 방식이 실제로 동작하려면 "질문과 관련된 자료를 빠르게 찾아내는" 기술이 필요한데, 그 역할을 벡터DB가 맡습니다.',
    ],
    note: '검색된 자료의 질이 나쁘면 답변의 질도 함께 나빠집니다. 엉뚱한 문서를 찾아오면 LLM은 그걸 근거 삼아 그럴듯하게 답할 뿐이라, "찾아온 자료가 정말 맞는 자료인가"를 확인하는 것도 중요합니다. ⚠️',
    flow: 'flowchart LR\n' +
          'A["질문"] --> B["벡터DB에서 검색"]\n' +
          'B --> C["관련 문서"]\n' +
          'C --> D["LLM"]\n' +
          'D --> E["답변"]',
    related: ['llm', 'vector-db', 'mcp'],
  },
  {
    id: 'vector-db',
    emoji: '🧭',
    term: '벡터DB',
    en: 'Vector Database',
    part: 'part07',
    kind: 'concept',
    short: '텍스트를 숫자 좌표(벡터)로 바꿔서, "의미가 비슷한 것"끼리 가깝게 모아 두는 저장소예요. 단어가 완전히 같지 않아도 뜻이 비슷하면 찾아낼 수 있다는 것이 핵심입니다. 예를 들어 "강아지"로 검색해도 "반려견"이라고 적힌 문서를 찾아낼 수 있어요. 🧭',
    body: [
      '일반 데이터베이스는 글자가 정확히 일치해야 찾아지지만, 벡터DB는 문장을 <strong>의미를 담은 숫자 좌표(벡터)</strong>로 바꿔 저장해 두고, 그 좌표끼리 얼마나 가까운지를 계산해서 찾습니다. 그래서 표현이 달라도 뜻이 비슷하면 찾아낼 수 있어요.',
      '<strong>RAG</strong>가 실제로 동작하려면 이 저장소가 꼭 필요합니다. 질문이 들어오면 그 질문도 벡터로 바꾼 뒤, 미리 저장해 둔 문서 벡터 중 가장 가까운 것들을 찾아 LLM에게 건네주는 식이에요.',
    ],
    related: ['rag', 'llm'],
  },
  {
    id: 'tool-calling',
    emoji: '🔧',
    term: 'Tool Calling',
    en: 'Tool Calling',
    part: 'part07',
    kind: 'concept',
    short: 'LLM이 혼자서는 못 하는 일—정확한 계산, 실시간 검색, 파일 조작 같은 것—을 외부 함수나 API를 "호출"해서 대신 처리하게 만드는 방식이에요. LLM이 "지금은 이 도구를 써야겠다"고 판단하면, 실제로 그 함수를 불러서 결과를 받아 옵니다. 말만 하는 게 아니라 실제로 행동하게 되는 첫걸음이에요. 🔧',
    body: [
      'LLM은 텍스트를 이어 붙이는 데는 강하지만, 큰 수를 정확히 계산하거나 지금 이 순간의 날씨를 아는 것처럼 <strong>스스로 할 수 없는 일</strong>이 많습니다. Tool Calling은 이럴 때 LLM이 "이 작업에는 어떤 도구가 필요하다"고 판단하고, 미리 정의해 둔 함수나 API를 실제로 호출하게 해 주는 방식입니다.',
      '예를 들어 "서울 날씨 알려 줘"라고 물으면, LLM은 날씨를 직접 알지 못하는 대신 날씨 API를 호출해서 실제 값을 받아온 뒤 그걸 바탕으로 답합니다.',
      '<strong>AI Agent</strong>가 검색하고, 파일을 고치고, 실제로 일을 해내는 것도 결국 이 Tool Calling이 여러 번 반복되는 것입니다. 에이전트의 손발이 되는 기초 기술인 셈이에요.',
    ],
    note: 'LLM이 아무 도구나 마음대로 만들어 쓰는 것은 아닙니다. 미리 "이런 도구를 이렇게 쓸 수 있다"고 정의해 둔 목록 안에서만 골라 호출합니다.',
    flow: 'flowchart LR\n' +
          'A["LLM 판단"] --> B["도구 호출"]\n' +
          'B --> C["함수 · API 실행"]\n' +
          'C --> D["결과 반환"]\n' +
          'D --> A',
    related: ['ai-agent', 'api', 'mcp', 'llm'],
  },
  {
    id: 'multimodal',
    emoji: '🌈',
    term: '멀티모달',
    en: 'Multimodal',
    part: 'part07',
    kind: 'concept',
    short: '텍스트뿐 아니라 음성·이미지·영상처럼 여러 형태(모달리티)를 함께 입력받거나 만들어 낼 수 있는 AI를 말해요. 글로만 대화하던 AI가 이제 목소리를 듣고, 그림을 보고, 이미지를 직접 그려 주기도 합니다. "모달"은 정보가 전달되는 형태를 뜻하는데, 그게 여러(multi) 개라는 뜻이에요. 🌈',
    body: [
      '예전 LLM은 텍스트만 주고받을 수 있었지만, 멀티모달 AI는 음성을 듣고 글로 옮기거나(음성인식), 글을 목소리로 읽어 주거나(TTS), 설명만으로 이미지를 그려 내는 것까지 할 수 있습니다.',
      '입력과 출력의 형태가 텍스트 하나로 고정되지 않는다는 것이 핵심입니다. 사진을 보여 주고 <strong>"이 안에 뭐가 있어?"</strong>라고 물을 수도 있고, 반대로 글로 설명해서 그림을 만들어 낼 수도 있어요.',
    ],
    related: ['llm'],
  },
  {
    id: 'langchain',
    emoji: '⛓️',
    term: 'LangChain',
    en: 'langchain.com',
    part: 'part07',
    kind: 'tool',
    short: 'LLM 호출, 프롬프트 작성, 외부 도구 연결처럼 AI 서비스를 만들 때 필요한 조각들을 사슬처럼 이어 붙여, 하나의 흐름(체인)으로 만들어 주는 개발 프레임워크예요. "질문을 받으면 → 문서를 찾고 → 그 내용을 참고해 답을 쓴다" 같은 절차를 손으로 다 짜지 않고 미리 준비된 조각들을 연결해서 만듭니다. RAG나 AI Agent를 직접 만들어 볼 때 특히 자주 등장하는 이름입니다. ⛓️',
    body: [
      '이름 그대로 여러 조각을 사슬(chain)처럼 이어 붙이는 것이 핵심 아이디어입니다. "질문을 받는다 → 관련 문서를 찾는다 → 그 문서를 참고해서 LLM이 답을 쓴다"처럼 여러 단계를 하나하나 직접 짜지 않아도, 미리 만들어진 조각들을 연결하기만 하면 됩니다.',
      '<strong>RAG</strong>(문서를 검색해서 답에 활용하는 방식)나 <strong>AI Agent</strong>(스스로 도구를 골라 쓰며 일을 처리하는 AI)를 만들 때 특히 자주 등장합니다. 검색, 저장, 도구 호출처럼 직접 짜려면 손이 많이 가는 부분들이 미리 만들어진 조각으로 제공되기 때문이에요.',
      'LLM 자체를 만드는 도구가 아니라, 이미 있는 LLM을 <strong>어떻게 조합해서 쓸지</strong>를 도와주는 프레임워크입니다. 그래서 어떤 LLM을 쓰느냐와는 별개로, "이 조각들을 어떤 순서로 엮을지"를 설계하는 데 집중합니다.',
    ],
    related: ['llm', 'ai-agent', 'rag', 'tool-calling'],
  },
  {
    id: 'notion-mcp',
    emoji: '🗒️',
    term: 'Notion MCP',
    en: 'Notion',
    part: 'part07',
    kind: 'tool',
    short: 'MCP(Model Context Protocol)라는 공통 규격을, 실제로 노션(Notion)에 연결해 둔 구체적인 서버예요. 이걸 붙이면 AI가 내 노션 워크스페이스의 페이지를 읽고, 내용을 정리해서 새 페이지로 저장하는 것까지 직접 할 수 있게 됩니다. "MCP는 규격, Notion MCP는 그 규격을 노션에 적용한 실제 사례"라고 생각하면 이해가 쉽습니다. 🗒️',
    body: [
      '예를 들어 "지난주 회의록에서 결정 사항만 뽑아서 새 페이지로 정리해 줘"라고 하면, AI가 <strong>Notion MCP</strong>를 통해 실제로 내 워크스페이스를 뒤져 회의록을 찾고, 내용을 정리한 뒤 새 페이지로 저장까지 합니다. 파일을 열어 복사·붙여넣기 하던 일을 AI에게 그대로 맡기는 셈이에요.',
      '<strong>MCP</strong> 카드에서 다룬 것처럼, MCP는 "AI를 바깥 도구에 연결하는 방법을 통일해 둔 규격"입니다. Notion MCP는 그 규격을 노션이라는 구체적인 서비스에 맞게 실제로 구현해 둔 서버 하나예요. 규격(MCP)과, 그 규격을 따르는 수많은 서버 중 하나(Notion MCP)의 관계로 이해하면 됩니다.',
      '이 과정 25회차 실습에서 직접 연결해 보며, 내 노션 페이지를 AI가 읽고 쓰게 만드는 과정을 실습으로 확인합니다.',
    ],
    note: '연결한다고 모든 페이지에 자동으로 접근할 수 있는 것은 아닙니다. 노션 안에서 어떤 페이지까지 AI에게 열어 줄지 직접 권한을 허용해 주어야 합니다. 🔐',
    related: ['mcp', 'ai-agent', 'tool-calling'],
  },

  /* ---- PART 08. 해커톤 ---- */
  {
    id: 'mvp',
    emoji: '🚀',
    term: 'MVP',
    en: 'Minimum Viable Product · 최소 기능 제품',
    part: 'part08',
    kind: 'concept',
    short: '완성품이 아니라, 핵심 가설을 확인할 수 있는 최소한의 기능만 담아 빠르게 만든 버전이에요. 모든 기능을 다 넣은 다음 세상에 내놓는 대신, "이게 진짜 필요한 게 맞나?"를 가장 빨리 확인할 수 있는 만큼만 만듭니다. PART 8에서는 이걸 실제로 손으로 만들어 봅니다. 🚀',
    body: [
      '예를 들어 "매일 할 일을 추천해 주는 앱"을 만든다면, 알림·통계·꾸미기 기능을 다 넣기보다 "추천이 정말 쓸모 있는가"부터 확인할 수 있는 한 가지 기능만 남기는 식입니다.',
      '<strong>MVP 집중 구현 4단계</strong>는 이렇게 만들 기능을 추리고, 빠르게 구현하고, 사람들에게 보여 주고, 반응을 반영하는 과정을 순서대로 밟습니다. 해커톤처럼 시간이 짧을 때 가장 효과가 큰 전략이에요.',
    ],
    note: '기능이 적다고 다 MVP는 아닙니다. 아무 기능이나 빼는 게 아니라, 확인하려는 가설에 필요한 기능만 남기는 것이 핵심이에요.',
    related: ['lean-startup', 'hackathon', 'capstone'],
  },
  {
    id: 'capstone',
    emoji: '🎓',
    term: '캡스톤',
    en: 'Capstone Project',
    part: 'part08',
    kind: 'concept',
    short: '과정에서 배운 것을 총동원해서 만드는 마무리용 종합 프로젝트예요. 기획, 디자인, 코딩, 데이터, AI 활용까지 그동안 따로따로 배운 것들을 하나의 결과물 안에 다 녹여내는 것이 목표입니다. 30회차 팀 빌딩으로 시작해서 과정 막바지까지 이어집니다. 🎓',
    body: [
      '"capstone"은 건물 맨 꼭대기에 얹어 마무리하는 돌을 뜻합니다. 그 이름처럼, 그동안 배운 여러 조각을 한데 모아 완성하는 자리라는 뜻을 담고 있어요.',
      '팀 단위로 진행되기 때문에 <strong>팀 빌딩</strong>에서 함께할 사람과 역할을 먼저 정한 뒤 시작합니다. 완성된 결과물은 그대로 <strong>포트폴리오</strong>에 담기는 경우가 많습니다.',
    ],
    related: ['team-building', 'hackathon', 'portfolio', 'mvp'],
  },
  {
    id: 'hackathon',
    emoji: '💡',
    term: '해커톤',
    en: 'Hackathon',
    part: 'part08',
    kind: 'concept',
    short: '정해진 짧은 기간 동안 집중해서 아이디어를 실제로 만들어 보고 발표하는 행사예요. "해킹(hacking)"과 "마라톤(marathon)"을 합친 이름처럼, 며칠 혹은 몇 시간이라는 제한된 시간 안에 몰입해서 결과물을 뽑아내는 것이 특징입니다. PART 8의 이름 자체가 "MVP 집중 구현 + 실전 해커톤"이에요. 💡',
    body: [
      '아이디어를 오래 고민하기보다 일단 만들어서 보여 주는 것에 무게를 둡니다. 그래서 <strong>MVP</strong>처럼 최소한의 기능만 빠르게 구현하는 전략과 궁합이 잘 맞습니다.',
      '이 과정에서는 "확장된 해커톤 프로젝트 시간"이라는 이름으로, 일반적인 해커톤보다 넉넉한 시간을 들여 캡스톤 프로젝트를 완성하는 데 씁니다.',
    ],
    related: ['mvp', 'capstone', 'team-building'],
  },
];
